### ISSUE TITLE
Grial NavigationBar in 3.0.62-RC is not applying BarTextColor but instead defaulting to black color

### ISSUE THREAD

**Issue by dknezevic1** [UXDivers/Grial-UI-Kit-Support#703] opened 2020-04-10 01:08 UTC
![image](https://user-images.githubusercontent.com/20426072/78953248-388ac600-7aa6-11ea-9b1c-adecbcc03a57.png)

![image](https://user-images.githubusercontent.com/20426072/78953186-07aa9100-7aa6-11ea-8bac-e6982029ea8c.png)

**Comment by jpbrocca** [comment] 2020-04-15 16:25
Hi @dknezevic1,

we could not reproduce your issue.
Which version of Xamarin Forms are you using?

Regards,
JP

**Comment by dknezevic1** [comment] 2020-04-15 17:47
I had to revert to 4.3 because 4.5 had other issues

**Comment by dknezevic1** [comment] 2020-04-17 18:16
Upgrading to the latest stable version of Xamarin Forms (4.5.0.617) fixed the color issue but the custom font (Billabong) is not being applied. I tried using the new approach for embedded font in Xamarin Forms 4.5, but that didn't work either.

**Comment by dirivero** [comment] 2020-04-20 21:39
We are working on a fix for the font family issue on the nav bar, it will be out soon.

**Comment by dirivero** [comment] 2020-05-08 19:54
The font family issue is fixed in version 3.0.62-RC.

**Comment by dirivero** [comment] 2020-06-27 02:57
We've just released version 3.0.70 including this fix. I will close the issue now.

**Closed by dirivero** 2020-06-27 02:57 UTC
