### ISSUE TITLE
Hyperlink

### ISSUE THREAD

**Issue by Onslot** [UXDivers/Grial-UI-Kit-Support#547] opened 2019-04-04 04:02 UTC
Hi 

I can not find an example in the sample for a hyperlink on xaml and click or tap event to open device default browser. Does it not have? If it does can you give me instructions how to get it done or pint me to the right files? I looked at xamarin.essesntials but i keep getting errors and it is not working.

**Comment by jpbrocca** [comment] 2019-04-04 12:05
Hi @Onslot,
there are not hyperlinks per se in Xamarin Forms, but you can use a `<Label>` and style it to look like one. 

There are plenty of samples in internet about them, such this:
https://www.davidbritch.com/2018/10/creating-hyperlink-in-xamarinforms.html

I am closing this because it is not a bug.

Regards,
JP

**Closed by jpbrocca** 2019-04-04 12:05 UTC
