### ISSUE TITLE
No embeddedresource found for __XamlGeneratedCode_

### ISSUE THREAD

**Issue by DavidSilverlight** [UXDivers/Grial-UI-Kit-Support#616] opened 2019-09-07 08:44 UTC
### Description

I just attempted to run the application and it crashes at LoadApplication with the following error and stack trace:

No embeddedresource found for __XamlGeneratedCode__.__Type5ffeda60fcc549be984c9c88385576b3

  at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.Type callingType) [0x00012] in D:\a\1\s\Xamarin.Forms.Xaml\XamlLoader.cs:69 
  at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml] (TXaml view, System.Type callingType) [0x00000] in D:\a\1\s\Xamarin.Forms.Xaml\ViewExtensions.cs:36 
  at __XamlGeneratedCode__.__Type5ffeda60fcc549be984c9c88385576b3.InitializeComponent () [0x00001] in /Users/DavidSilverlight/Xamarin/App_Holiday/git/HolidayStores/GrialV1/Holiday/obj/Debug/netstandard2.0/Styles/AppFontFamilies.xaml.g.cs:28 
  at __XamlGeneratedCode__.__Type5ffeda60fcc549be984c9c88385576b3..ctor () [0x00008] in /Users/DavidSilverlight/Xamarin/App_Holiday/git/HolidayStores/GrialV1/Holiday/obj/Debug/netstandard2.0/Styles/AppFontFamilies.xaml.g.cs:23 
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:882 

### Steps to Reproduce

1. Downloaded project and restored nuget packages
2. Attempted to run the application 
3. App crashes with "No embeddedresource found for __XamlGeneratedCode__.__Type5ffeda60fcc549be984c9c88385576b3"

### Expected Behavior

App should run

### Basic Information

- Version with issue:
- Last known good version:3.0.46
- IDE: VS 2019 for mac
- Platform Target Frameworks: 
  - iOS:  12.4
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by dirivero** [comment] 2019-10-04 21:01
Hi David. 
I can't reproduce this problem. Is it still happening?
Have you changed the linker configuration? I've seen similar problems when choosing the link all option, check https://github.com/UXDivers/Grial-UI-Kit-Support/issues/624

**Comment by dirivero** [comment] 2019-10-17 21:56
I'm going to close this one. Feel free to reopen if you still have problems with it.

**Closed by dirivero** 2019-10-17 21:56 UTC
