### ISSUE TITLE
Gorilla SDK needed

### ISSUE THREAD

**Issue by attrib75** [UXDivers/Grial-UI-Kit-Support#273] opened 2017-10-10 18:23 UTC
We purchased the full license, I deployed the gorilla player from the downloaded source.  When I preview pages in the full sample solution, I'm seeing 'Gorilla SDK Needed' on most pages.

thanks

**Comment by LeoHere** [comment] 2017-10-10 19:13
@attrib75 You should run Grial using the Gorilla configuration, as described [here](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player).

**Comment by LeoHere** [comment] 2017-10-10 19:38
Ok, cool!. Please remember to close the issue once you are all set! Tks

**Comment by attrib75** [comment] 2017-10-11 13:37
Ok so I downloaded full sample, Gorilla ready, then built under Gorilla build configuration.  Still getting 'Gorilla SDK Needed'

**Comment by attrib75** [comment] 2017-10-11 13:54
this is so buggy I'm regretting buying it.  You guys have a long way to go.  Unfortunately I'm stuck with it now since we've already invested money

**Comment by attrib75** [comment] 2017-10-11 13:55
Virtually nothing works

**Comment by attrib75** [comment] 2017-10-11 14:32
Looks like you're shipping more than one version of your shared assembly

![image](https://user-images.githubusercontent.com/1398909/31447217-13cb1bb6-ae67-11e7-8749-720a31506920.png)

**Comment by attrib75** [comment] 2017-10-11 14:33
I'm missing classes found in the shared assembly when I build the 'starter' vs the full

**Comment by attrib75** [comment] 2017-10-11 14:33
If you can make this work I have more projects to license.

**Comment by LeoHere** [comment] 2017-10-11 15:45
@attrib75 did you just build using Gorilla configuration or did you run your project using Gorilla configuration? You should run the project using Gorilla configuration as described in the link I share [above](http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player). That will start gorilla SDK.

Can you elaborate a bit more on this "I'm missing classes found in the shared assembly when I build the 'starter' vs the full"? what classes are missing?

**Comment by LeoHere** [comment] 2017-10-11 16:31
@attrib75 this animated gif illustrates what you need to do: 

![grialgorilla4](https://user-images.githubusercontent.com/16000584/31453362-46937ed2-ae88-11e7-81ea-5a6184b640c9.gif)

**Comment by attrib75** [comment] 2017-10-11 16:44
Its not design time if you have to run the project

**Comment by attrib75** [comment] 2017-10-11 16:46
As far as the missing assembly issue:  There are two samples available for download when you purchase the grial kit.  One is a full sample, one is a starter sample.  Inside those samples is an assembly:  uxdivers.artina.shared.  Those assemblies are different (pictured above) depending on what samples you look in.  You cannot copy code from the full sample into the starter one because types will be missing

**Comment by LeoHere** [comment] 2017-10-11 16:52
@attrib75 You should run in Gorilla mode when you want to design your pages. You will be able to preview them, edit them, add new ones, etc; which are the typical activities you want to do while designing your app. 

You just need to run the app once to setup Gorilla preview.

**Comment by attrib75** [comment] 2017-10-11 16:59
Ok, running in Gorilla mode like your example above still produces errors.  Virtually none of the pages work. 

![image](https://user-images.githubusercontent.com/1398909/31454599-8e1dba5e-ae7b-11e7-965c-2d87a5e8a85b.png)

![image](https://user-images.githubusercontent.com/1398909/31454640-aef8fce8-ae7b-11e7-9986-f751d648b591.png)

**Comment by LeoHere** [comment] 2017-10-11 17:02
@attrib75 can you please try restarting Gorilla? There is no need to run the mobil app again, just open it again in the simulator. After it is connected to Gorilla, try previewing a page again.

**Comment by attrib75** [comment] 2017-10-11 17:04
Which one?  There are 3 now.  One I installed somehow separately, one from the full sample app, one from the starter app

**Comment by LeoHere** [comment] 2017-10-11 17:06
If the same if you open the starter or the full sample app. You should only make sure that it is the app deployed using Gorilla Configuration.

**Comment by attrib75** [comment] 2017-10-11 17:07
Are you familiar with this error?  This is from running the 'starter' sample in debug mode

![image](https://user-images.githubusercontent.com/1398909/31454935-b46438c2-ae7c-11e7-9a5d-11a87859eda2.png)

**Comment by LeoHere** [comment] 2017-10-11 17:24
@attrib75 I'm trying with the same solutions you downloaded (i.e. your customized version of Grial) just in case there is something going on there but I can't reproduce the issues you are experiencing. 

I think that the shortest path to solving this issue might be to make a quick call so I can check what is going on in your side. Is that an option for you?

**Comment by LeoHere** [comment] 2017-10-11 17:36
@attrib75 If it is too late for you today, write me to l r o d r i g u e z at uxdivers.com and we will coordinate a suitable time for that call.

**Comment by attrib75** [comment] 2017-10-11 17:44
I would absolutely have a call today.  Thanks.  I have more projects to build and get licenses for.  I'll send you an email to exchange numbers.

**Comment by jpbrocca** [comment] 2017-11-09 11:44
Closing issue since the user was called and his issues were fixed.

**Closed by jpbrocca** 2017-11-09 11:44 UTC

**Comment by davidmalach** [comment] 2019-04-16 17:37
I am having the same problem.  How was this issue resolved?
