### ISSUE TITLE
[QUESTION] Is GridOptionView adapted to my needs?

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#207] opened 2017-07-21 09:40 UTC
Hello,

I would like to use the "_DashboardCardsPage_" to show many items trough CardViews, instead of using Lists, that only allow 1 item per row.

**_If I get more than 50 items, is this adapted to my need? Or could this cause performances problems?_**

From my first testing, this works correctly, but the loading time is important:
- I would like to know is there is a way to load the images in a Background Task, by showing first a default image
- I also would like to know if it is possible to render "dynamic" the loading of the items, as we could do on a ListView with ItemAppearing

Thanks in advance,

**Comment by LeoHere** [comment] 2017-07-22 11:11
The `GridOptionView` was not designed to handle lot of items. So probably you might get into performance issues if you add too many items, specially if those items are heavy, e.g. include images.

[FFImageLoading](https://github.com/luberda-molinet/FFImageLoading) is a excellent library for image loading. It can help you with the placeholder image, background downloading, cache and many other things.

Also, if you have images in your cards it will help you with performance, since it removes images while they are not visible.

**Comment by Goldstrike** [comment] 2017-07-31 13:21
Hi @LeoHere, thanks for your feedback. 

For my tests, I use `GridOptionsView` to display about 100 items: the loading time is a bit long, but the scroll of the items is quick. I tried to add a dynamic load of the data (20 per 20), but this time the performances are disappointing...

So I think that I will use `GridOptionView` to display the 10 first items, and then use another view to display all the items.

**Comment by Goldstrike** [comment] 2017-07-31 14:44
I have one more question about the "_DashboardCardsPage_": in your sample, the "_DashboardCardItemTemplate_" has a method "_OnCardTapped()_", but when we click on a card, nothing happens. 

**Is it normal?
Is there a way to bind an event to the related ViewModel  ("_DashboardCardsViewModel_")?**

**Comment by LeoHere** [comment] 2017-08-02 18:38
We were able to reproduce the issue in Android. We will further investigate it and come back to you. 

You can use commands to bind the event to the ViewModel using the `ItemClickedCommand` property of the `GridOptionsView`.

In order to use the `ItemClickCommand` property you need to:

1. Create the command object in the view model and expose it as a property. 

~~~
public class MyViewModel
{
	private readonly Command _itemCommand;

	public MyViewModel()
	{
		_itemCommand = new Command<MyItemType>(ItemAction);
	}

	public List<MyItemType> Items { ... }

	public ICommand ItemCommand => _itemCommand;

	private void ItemAction(MyItemType item)
	{
		// Action logic goes here...
	}
}
~~~

In the example, the property is called ```ItemCommand```.

2. Bind the ```ItemClickCommand``` to the command property (i.e. ```ItemCommand```)

~~~
<artina:GridOptionsView 
	ItemClickCommand="{Binding ItemCommand}"
	ItemsSource="{Binding Items}">
	<artina:GridOptionsView.ItemTemplate>
		<DataTemplate>
			...
		</DataTemplate>
	</artina:GridOptionsView.ItemTemplate>
</artina:GridOptionsView>
~~~

**Comment by LeoHere** [comment] 2017-08-03 10:57
@Goldstrike this seems to be a Form's issue (see [this](https://forums.xamarin.com/discussion/73228/tapgesturerecognizer-working-on-ios-but-not-on-android) for example).

In order to workaround it you can set `InputTransparent="true"` in the main `Grid` of the `DashboardCardItemTemplate`. That will fix the issue and work fine in iOS too.

Please, remember to close the issue if you considere it solved.

**Comment by Goldstrike** [comment] 2017-08-03 16:07
Thanks for your feedback.
In your opinion, what is the best way to manage the navigation on a detail's page from the Dashboard?
- from the **ViewModel**, with the "**_ItemClickCommand_**" command?
- from the **Code Behind**, with the "**_OnCardTapped()_**" method?

**Comment by Goldstrike** [comment] 2017-08-03 16:23
I tried your suggestion through the **ViewModel**, but for now it doesn't work: I never enter in the **_AgendaItemViewDetailAction()_** ...

Here is the ViewModel:
```
public class AgendaEventDashboardViewModel : ViewModelBase
{	
    ...
	
	public RelayCommand InitializeCommand { get; set; }

	private readonly Command _agendaItemClickCommand;
	public ICommand AgendaItemClickCommand => _agendaItemClickCommand;

	public AgendaEventDashboardViewModel(IAdpService adpService)
	{
		this._adpService = adpService;
		InitializeCommand = new RelayCommand(() => InitializeAsync());
		
		_agendaItemClickCommand = new Command<AgendaEvent>(AgendaItemViewDetailAction);
	}

	private void AgendaItemViewDetailAction(AgendaEvent item)
	{
		var agendaEvent = item;
	}
	
	...
}
```

And the View:
```
<artina:GridOptionsView
	Margin="0"
	...
	ItemsSource="{ Binding AgendaEventList }"
	ItemClickCommand="AgendaItemClickCommand">
	<artina:GridOptionsView.ItemTemplate>
		<DataTemplate>
			<local:AgendaEventItemTemplate HeightRequest="296" />
		</DataTemplate>
	</artina:GridOptionsView.ItemTemplate>
</artina:GridOptionsView>
```

**Did I miss anything?**

**Comment by LeoHere** [comment] 2017-08-03 18:07
This `ItemClickCommand="AgendaItemClickCommand"` should be `ItemClickCommand="{Binding AgendaItemClickCommand}"`.

After that, if still does not invoke the method in Android, be sure to do the  `InputTransparent="true"` thing I mentioned earlier.

**Comment by Goldstrike** [comment] 2017-08-04 10:26
Thanks it's better like that ;-)

But I have a last question, as I asked you previously: what is the best way to manage the navigation to a detail's page from the Dashboard?
- from the **ViewModel**, with the "`ItemClickCommand`" command?
- from the **code behind**, with the "`OnCardTapped()`" or another method?

I can now know the item that is clicked in the ViewModel, but I don't see how to navigate to the detail's page from the ViewModel: is there a "proper" way to navigate to the detail's page? (but in this case, the ViewModel must "know" the View)

Or is it more "clean" to get the clicked item directly in the code behinds? 
- I tried to replace the "`ItemClickCommand`" by a method in the code behind, but it didn't work
- and I don't see how to get the clicked item with "`OnCardTapped()`"

**Comment by Goldstrike** [comment] 2017-08-04 15:49
I have finally managed to do this through `OnCardTapped()`

```
var selectedAgendaEvent = (AgendaEvent)((VisualElement)sender).BindingContext;
var agendaEventView = new AgendaEventViewPage(selectedAgendaEvent);
await Navigation.PushAsync(agendaEventView);
```

Thank you again for your help!

**Closed** 2017-08-04 15:50 UTC
