### ISSUE TITLE
Gorilla Player Not Pulling Through Text

### ISSUE THREAD

**Issue by nialmcshane** [UXDivers/Grial-UI-Kit-Support#485] opened 2018-09-12 08:59 UTC
Hi,

I have downloaded the full sample - Gorilla ready and when I launch no text is pulling through from the resx file.

When I long hold on the player and go into the settings and look under culture it says it is "Not Available".

Can you please help?

Thanks,

**Comment by LeoHere** [comment] 2018-09-12 09:29
@nialmcshane please answer the following questions in order to narrow down the issue:

1. Are you seeing this issue in the solution downloaded from the Grial Admin without modifications? or did you do some changes?
2. What version of Gorilla are you using? 
3. Did you define more than one culture in the Grial Admin?
4. Can you please attach a screenshot of what you are seeing?

**Comment by nialmcshane** [comment] 2018-09-12 09:46
Hi, 

1. I have not made any modifications. 

2. Gorilla 1.2.2.0

3. I did manage to get an example working by adding a new culture through the admin, by long holding it came up in the settings and I managed to get text coming through but I do not want this so I cleared it and tried again.

4. See attached phone screenshot

![screenshot_20180912-103634](https://user-images.githubusercontent.com/31505485/45417010-15552600-b679-11e8-9a2d-13b6a5009420.png)

**Comment by nialmcshane** [comment] 2018-09-12 10:44
Hi, does the .NET Framework error below have a bearing on this?

![default net-version](https://user-images.githubusercontent.com/31505485/45420135-4174a500-b681-11e8-9e61-ced2488e2566.jpg)

**Comment by nialmcshane** [comment] 2018-09-12 10:52
Is it something to do with targeting Oreo 8.1?

**Comment by LeoHere** [comment] 2018-09-12 12:01
@nialmcshane send me an email to l r o d r i g u e z at uxdivers.com and I will send you a dev version of  Gorilla that might fix this issue.

**Comment by IoTFier** [comment] 2018-09-12 14:49
Hi @nialmcshane 
I experience this issue many times as well. 
Try to open the gorilla.json and save that file (even with no changes); it triggers some type of events (Grial team will have a better handle on it) forcing Gorilla server to push content to the Gorilla player.
Not necessarily a good experience; but we are lucky to have one of the best XAML previewer delivered by this team.

Good luck.

**Comment by LeoHere** [comment] 2018-09-14 11:03
@nialmcshane confirmed the issue is solved in Gorilla `1.2.14` (not publicly available yet). Use the workaround mentioned by @IoTFier for previous versions of Gorilla. 

@IoTFier or anyone experiencing the issue, if you want access to `1.2.14` write me to the email above and I will share it with you.

**Comment by IoTFier** [comment] 2018-09-22 13:12
Hi @LeoHere, using the dev version of Gorilla 1.2.14, my app keeps crashing on Android when I try to preview stock copy of TabControlAndroidSamplePage. 
Any thoughts on that?
When do we expect the next stable version of Gorilla? Is it going to be compatible with XF 3.2?

Thank you.

**Comment by LeoHere** [comment] 2018-09-25 13:03
@IoTFier I just sent you an email. The version I sent you is compatible with 3.2.

**Comment by IoTFier** [comment] 2018-10-09 00:53
Hi @LeoHere, when is the next GA version of Gorilla coming?
I have opened a issue under Gorilla player support -  https://github.com/UXDivers/Gorilla-Player-Support/issues/307 . Any of your help will be appreciated.

Got new Gorilla dev version ?

Thanks,

**Comment by LeoHere** [comment] 2019-01-02 11:43
Closing the issue to keep things tidy. Please reopen it again if you need to.

**Closed by LeoHere** 2019-01-02 11:43 UTC
