### ISSUE TITLE
ListView selection colour the same as AccentColor

### ISSUE THREAD

**Issue by ghost** [UXDivers/Grial-UI-Kit-Support#8] opened 2015-12-05 10:34 UTC
The colour used for the currently selected ListView item is the same as the AccentColor - which is also used for ListView item text. Therefore when an item is selected, the text is invisible.

We need to use different colours for these two items.

**Comment by james-lavery** [comment] 2015-12-05 10:47
Further information (should have put this in the initial issue).

This occurs on both iOS and Android, and in my project and the Grial demonstration project.

**Comment by james-lavery** [comment] 2015-12-05 10:50
Screenshot of Grial demo on iOS...

![simulator screen shot 5 dec 2015 10 49 24](https://cloud.githubusercontent.com/assets/1755678/11607428/e591a79e-9b3d-11e5-8490-f5cb12afa57e.png)

**Comment by jpbrocca** [comment] 2015-12-05 11:20
Good catch! 
Thanks James!

**Comment by jpbrocca** [comment] 2015-12-05 11:52
I cannot reproduce it on Android...this is how our sample looks:

![image](https://cloud.githubusercontent.com/assets/15996999/11607653/73bef6ea-9b2d-11e5-85ca-b296e737826b.png)

**Comment by james-lavery** [comment] 2015-12-05 12:31
You are right - Android is ok. However I've just checked iOS having rebuilt the sample, and I'm definitely seeing the behaviour there - the same as my earlier screenshot.

**Comment by jpbrocca** [comment] 2015-12-05 12:37
Ok, I will investigate on iOS. Thanks! :)

**Comment by noxe** [comment] 2016-02-22 18:38
Has this already been fixed? Or is there an Workaround?

**Comment by jpbrocca** [comment] 2016-02-23 14:11
Hi @noxe,

We have a fix for this.
If you could tell me your order number I can send you an email with this fix.

Thanks,
JP

**Comment by ahmedkhan25** [comment] 2016-03-17 17:22
Hi I'm having the same issue for a ListView

Both the Selected Item and The GroupShortName background is stuck in the Grail Accent color

![image](https://cloud.githubusercontent.com/assets/1980889/13854724/db846a90-ec3a-11e5-9ef0-a68b5eb8fd80.png)

**Comment by jpbrocca** [comment] 2016-03-17 19:16
Hi @ahmedkhan25,
I sent you an email with the new dlls that fixes this issue.

Regards,
JP

**Comment by jeremykirkup** [comment] 2016-04-13 17:57
Hi Could I have the fix for this also?  I have the same issue with the text color.

Registered email for the order is jeremykirkup@hotmail.com order was placed on 22nd March 2016

Many thanks

Jeremy

**Comment by traviswaldorf** [comment] 2016-11-06 00:31
I need these .dlls as well. Going through the same problem.

**Comment by marcelojmacedo** [comment] 2017-08-30 13:39
Hi, I have the same problem. marcelo@mira.eti.br

**Comment by dirivero** [comment] 2019-10-05 17:26
There's a color in Grial 3 themes to control this color from Xaml:

```
<Color x:Key="ListViewSelectedItemBackgroundColor">#11000000</Color>
```

**Closed by dirivero** 2019-10-05 17:26 UTC
Labels: bug
