### ISSUE TITLE
Grial UI Kit generated solution causes issue with Xam.Plugin.Media nuget on iPad model MP2F2LL/A

### ISSUE THREAD

**Issue by bobvaselaar** [UXDivers/Grial-UI-Kit-Support#333] opened 2017-12-19 20:35 UTC
Found this issue while testings my Grial-based app on iPad model MP2F2LL/A:

I use the Xam.Plugin.Media Nuget  https://github.com/jamesmontemagno/MediaPlugin for camera support in my app. 

When I try to take a picture with the iPad the application will freeze up either on the first picture or the second picture.

When I created a simple Xamarin forms project with the same architecture, no bug was observed. 

Both projects (Grial and standard Xamarin Forms) work fine with iPhone model MG5X2LL/A.

**Comment by dirivero** [comment] 2017-12-20 00:17
I've tried with both projects but I couldn't reproduce the issue in either of them. 

What's the error you are experiencing? Exception?

Thanks
Diego

PS: I've removed the zips from your post since it's not allowed to share publicly Grial source code.

**Comment by bobvaselaar** [comment] 2017-12-20 15:44
Hi Diego,

Thanks for giving this a try. Unfortunately, no, there is no exception that
I've seen (or even a crash). The app simply becomes totally unresponsive as
soon as it his the code

await CrossMedia.Current.TakePhotoAsync(MediaOptions options)

I've observed this on the listed iPad model with both iOS 11.2 and 11.3.
Which version were you using? What was the model number of your iPad?

Strangely I haven't found any issues with iPhone, although my test
environment is currently limited to two devices.

That being said, I don't think iPad support will be critical for our app.
It's an insurance industry app directed and policy holders and agents, and
submitting claims with iPads is unlikely. With this is mind, I don't think
I'll spend much more time on this bug - we'll simply release without iPad
support.

Any insight would be appreciated.

thanks!

Bob

**Comment by LeoHere** [comment] 2018-02-26 10:38
This is an old post, and probably you already had moved on with this, but we recently have found the cause of this issue.

[This](http://www.openradar.me/30396879) is the issue we are hitting. The camera slider is causing the issue.

A possible workaround for this issue is:

Instead of doing this:

~~~
    UXDivers.Artina.Shared.GrialKit.Init(new ThemeColors(), "......GrialLicense");
~~~
do this
~~~
    UXDivers.Artina.Shared.GrialKit.Init(null, "......GrialLicense");
~~~

By passing null non of the appearance colors will be set by Grial.

After invoking `Init()` do this:

~~~
            var colors = new ThemeColors();
            var accentColor = colors.GetColor("AccentColor");

            UIProgressView.Appearance.ProgressTintColor = accentColor;

            //UISlider.Appearance.MinimumTrackTintColor = accentColor;
            //UISlider.Appearance.MaximumTrackTintColor = accentColor;
            UISlider.Appearance.ThumbTintColor = accentColor;

            UISwitch.Appearance.OnTintColor = accentColor;

            UITableViewHeaderFooterView.Appearance.TintColor = accentColor;

            UITableView.Appearance.SectionIndexBackgroundColor = accentColor;
            UITableView.Appearance.SeparatorColor = accentColor;

            UITabBar.Appearance.TintColor = accentColor;

            UITextField.Appearance.TintColor = accentColor;

            UIStepper.Appearance.TintColor = accentColor;
~~~

These lines mimics what the `Init` method does internally during initialization to set the appearance colors. The problematic lines are commented out.

**Comment by LeoHere** [comment] 2018-02-26 10:39
Closing the issue now. Feel free to open it again is you need so.

**Closed by LeoHere** 2018-02-26 10:39 UTC

**Comment by upskydownshoes** [comment] 2019-01-29 01:16
Nice one Leo, that stumped me for a week! Couldn't find UISlider.Appearance.MinimumTrackTintColor  nor 
UISlider.Appearance.MaximumTrackTintColor anywhere and I knew they were the offending items! Good man!
