### ISSUE TITLE
Splash Screen IOS

### ISSUE THREAD

**Issue by QamarAftab** [UXDivers/Grial-UI-Kit-Support#314] opened 2017-11-15 12:51 UTC
Splash Screen in ios Does not change .. 
i Replace Image In  ios 
\Grial\full\iPayTax.iOS\Resources\splash@2x.png
but Still showing Grial Splash screen

**Comment by jpbrocca** [comment] 2017-11-15 14:17
Hi @QamarAftab,

That is weird. Probably a cache issue.
Try performing a Clean and Rebuild, then run again and let me know if the image is changed.

Keep also in mind you should provide the image for all different pixel densities (i.e.: splash.png, splash@3x.png).

Best
JP

**Comment by lerrie** [comment] 2017-12-27 18:49
Hi, i am having the same issue. I updated the splash.png image and the splash does not change.. it still has the Grial icon. I even removed the storyboard and add new blank one, uploaded LaunchImages under Asset.. and still the same. 

Please advise. Thank you.

**Comment by jpbrocca** [comment] 2017-12-27 19:29
Hi @lerrie,

Did you make sure to update all different versions of your image (i.e.: splash.png, splash@3x.png).?
Can you confirm?

Thanks,
JP

**Comment by lerrie** [comment] 2017-12-27 19:42
Hi JP,

Yes i have those three - splash.png, splash@2x.png and splash@3x.png.

It is weird because when i open the storyboard in VS, it is showing my logo but when i run to ipad device, it is showing the grial logo. 

You mentioned something about the cache?, how will I reset or clear the cache? I already did the clear, build and rebuild few times.. and no luck.

Thanks,
Lerrie

**Comment by jpbrocca** [comment] 2017-12-27 20:22
Hi @lerrie,

OK, you did the clean, rebuild stuff so that should have updated things with your splash.

Can yo do a couple of things more?

1. In any xaml file add an image an set its source to your splash, the run and check you have the right image there on your ipad.
2. Close VS, clean, rebuild and run again.

If all that fails please let me know.

Thanks
JP

**Comment by lerrie** [comment] 2017-12-27 21:56
Hi JP, i tried what you said and the image shows fine. Surprisingly, my logo shows up in the storyboard too. I am not sure what solves it but another thing i did is remove and then copy and paste the original storyboard from the starter project to my project. Thank you for your quick response and assistance.

**Comment by jpbrocca** [comment] 2017-12-27 22:53
Hi @lerrie,
Glad to 'read' that 😀

Yes, probably some VS hiccup. Sometimes VS seems not to update things when it builds.
I often find myself doing the clean, build and run combo and when that fails I restart VS and 90% of the times it works!

Best regards and you are welcome!
JP

P.S.: closing this issue since it seems is not a bug on our end.

**Closed by jpbrocca** 2017-12-27 22:53 UTC
