### ISSUE TITLE
[Question] Could I use Iconize with GrialKit

### ISSUE THREAD

**Issue by Goldstrike** [UXDivers/Grial-UI-Kit-Support#234] opened 2017-09-05 11:02 UTC
Hello,

I've already asket this question previously, but the [issue](https://github.com/UXDivers/Grial-UI-Kit-Support/issues/215) was closed.

I've finally tried to use Iconize in my project: for this I had to updated some nugets packages, like Xamarin.Forms.

I've edited the `NavigationPageHelper` to replace `NavigationPage` by `IconNavigationPage`:
```
public static class NavigationPageHelper
{
    public static NavigationPage Create(Page page)
    {
        //return new NavigationPage(page) { BarTextColor = Color.White };
        return new IconNavigationPage(page) { BarTextColor = Color.White };
    }
}
```

On Android, this works fine, but on iOS, the NavBar has no longer its background color...

_**Would you have an explanation?**_

**Comment by LeoHere** [comment] 2017-09-05 16:46
Did you updated the Implicit style defined on the `App.xaml`?

~~~
<Style TargetType="NavigationPage">
	<Setter Property="BarBackgroundColor" Value="{ DynamicResource AccentColor }"/>
	<Setter Property="BarTextColor" Value="{ DynamicResource InverseTextColor }"/>
</Style>
~~~

This might be the cause...

**Comment by Goldstrike** [comment] 2017-09-05 16:53
No I haven't updated the implicit style. Should I do it?

For now, I have 2 results:
- with the "default" [NavigationPage]:
 (https://img11.hostingpics.net/pics/399509WithoutIconizeNavBar.png)
- with the "Iconize" [NavigationPage](https://img11.hostingpics.net/pics/905241WithIconizeNavBar.png):

**Comment by Goldstrike** [comment] 2017-09-05 19:08
Hi @LeoHere 
I finally found a solution:

- I've created a custom control from the Iconize's page (`IconNavigationPage`):
```
public class LogoNavigationPage : IconNavigationPage
{
    public LogoNavigationPage(Page root) : base(root)
    {
    }
}
```

- then, I've duplicated the implicit style that you mentioned:
```
<Style TargetType="local:LogoNavigationPage">
    <Setter Property="BarBackgroundColor" Value="{ DynamicResource AccentColor }"/>
    <Setter Property="BarTextColor" Value="{ DynamicResource InverseTextColor }"/>
</Style>
```

- and now I've the expected rendering on iOS:
[screenshot1](https://img11.hostingpics.net/pics/921565WithIconizeNavBarAfterUpdate.png)

**_Is this a good approach?_**

But I've another request: is there a way to customize the StatusBar with GrialKit?
- on iOS, it's current to have the same color on the NavBar and the StatusBar
- but on Android, it's more common to have a "darker" color for the StatusBar
 
After having updated the Nuget packages to install Iconize on my project, I've remarked that the StatusBar is now colored on Android. But the StatusBar has the same color than the NavigationBar:
[screenshot2](https://img11.hostingpics.net/pics/937736WithIconizeAndroid.png)

**_Is there a way to manage this easily?_**

**Comment by jpbrocca** [comment] 2017-09-06 18:21
Hi @Goldstrike, how are you?

Didn't try it, but could you try to use the following for the NavigationPage implicit style on your App.xaml?
```
<Style TargetType="NavigationPage" ApplyToDerivedTypes="true">
    <Setter Property="BarBackgroundColor" Value="{ DynamicResource AccentColor }"/>
    <Setter Property="BarTextColor" Value="{ DynamicResource InverseTextColor }"/>
</Style>
```
Notice the `ApplyToDerivedTypes="true"`...this should do the trick, but if it doesn't work please let me know.

**About the Status Bar color:**

- You can change it on your android project if you change in `Style.xml`:
```
Grial.Droid
    |_ Resources
        |_ values-v21
            |_ Style.xml
```

...the value for `colorPrimaryDark` (in this sample I just mapped it to the AccentColor):

```
<!-- colorPrimaryDark is used for the status bar -->
<item name="colorPrimaryDark">@color/AccentColor</item>
```

Regards,
JP

**Comment by Goldstrike** [comment] 2017-09-06 19:22
Hi @jpbrocca 
It works fine with `ApplyToDerivedTypes="true"`, thank you.

About the Android primary dark, I've created a new color in the `GrialLightTheme.xaml`:
`<Color x:Key="DarkAccentColor">#FF0086AF</Color>`

And then I tried to use it in the `Style.xaml`:
`<item name="android:colorPrimaryDark">@color/DarkAccentColor</item>`

But this didn't work:

> Error: No resource found that matches the given name (at 'android:colorPrimaryDark' with value '@color/DarkAccentColor').

Is there a way to fix it?

**Comment by jpbrocca** [comment] 2017-09-06 21:11
Hi @Goldstrike,
great! :)

In order to make the build task to synchronize the colors both of them need to be present in the platform colors **AND** in your XAML theme.

That means that, you will need to add the new color (`DarkAccentColor`) and its value:
 on `Colors.xml`:
```
Grial.Droid
    |_ Resources
       |_ values
          |_ Colors.xml
```
`<color name="DarkAccentColor">#FF0086AF</color>`

Since you already added it in your theme (XAML): 
`<Color x:Key="DarkAccentColor">#FF0086AF</Color>`

...the build task will make sure to sync both next time you change `DarkAccentColor` on your XAML theme.

Best,
JP

**Comment by Goldstrike** [comment] 2017-09-07 07:12
Hi @jpbrocca  thanks again!
For time, this doesn't work...
Is there something else?

I've defined the color in the following files:
- `GrialLightTheme.xaml`:
```
<!-- New color : dark accent color for Android Status Bar -->
<Color x:Key="DarkAccentColor">#FF0067A3</Color>
```

- `Colors.xml`:
```
<color name="DarkAccentColor">#FF0067A3</color>
```

-  `Style.xml `:
```
<!-- Theme -->
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
	<!-- Set AppCompat’s color theming attrs -->
	<!-- colorPrimary is used for the default action bar background -->
	<item name="colorPrimary">@color/AccentColor</item>
	<!-- colorPrimaryDark is used for the status bar -->
	<item name="colorPrimaryDark">@color/DarkAccentColor</item>
        ...
	<!-- Main theme colors -->
	<!--   your app branding color for the app bar -->
	<item name="android:colorPrimary">@color/AccentColor</item>
	<!--   darker variant for the status bar and contextual app bars -->
       <item name="android:colorPrimaryDark">@color/DarkAccentColor</item>
```

But this doesn't work: [screenshot](https://img11.hostingpics.net/pics/113634AndroidStatusBar.png)

What's wrong?

**Comment by jpbrocca** [comment] 2017-09-07 09:29
Hi @Goldstrike, how are you?
Hmmm...is a little bit hard to tell you without seeing the whole project stuff.
The only thing I noticed is that you have defined twice the `colorPrimaryDark` on Style.xml (last line is prefixed with `android:`.

A few questions:

- Wich is your device and it's Android API version?
- How is your project target android version set?

Best
JP

**Comment by Goldstrike** [comment] 2017-09-07 16:00
Yes I defined `colorPrimaryDark` twice, as didn't know which one I need to use.

My device is a **Meizu m2 Note**, and its Android API version is **22** (Android 5.1).
The "Target Android version" is setted on "Use Compile using SDK version".

**Comment by jpbrocca** [comment] 2017-09-07 17:53
Ok, can you try setting Target Android version to API 21 or above and let me know?

**Comment by Goldstrike** [comment] 2017-09-08 17:08
I've tried this, it didn't change anything...

I could create you an account on my Git repository if you prefer, it's could be helpful so for another issue on [iOS debug](https://github.com/UXDivers/Grial-UI-Kit-Support/issues/216).

**Comment by jpbrocca** [comment] 2017-09-08 18:02
Ho @Goldstrike, how are you?
That is very weird.

When you downloaded the sample from Grial Admin and you compiled it, how did you see the status bar? (It should look black with text in white color).

**Comment by Goldstrike** [comment] 2017-09-09 17:48
@jpbrocca : no I didn't have the status bar initially.
But I wasn't able to install an old version of Iconize, and the last version recquires a recent version of Xamarin.Forms nugets packages.
After having updated the packages, the status bar get the color of the navigation bar.

**Comment by jpbrocca** [comment] 2017-09-11 17:38
Hi @Goldstrike, how are you?
Ok, can you please tell me which packages you updated?
I suspect this is an issue with Xamarin Android package, but I am not really sure.
From Grial perspective we are not doing anything different as in the sample you downloaded, and the way you used to change the status is through the platform so it should work.

I don't think this could be related to Iconize, so my guess is the issue is with the Xamarin Android pakages.

Regards and thanks
JP

**Comment by Goldstrike** [comment] 2017-09-11 19:10
Yes you're probably right: this could be for the latest Android packages.
But that means that Grial Kit is not fully compatible with these packages?
Would I need to wait an update?

**Comment by jpbrocca** [comment] 2017-09-11 20:32
I mean, if you tell me your packages version I could test and try to see if is there any workaround.

You offered to share your project so we can take a deeper look, so, can you send me an email to jpbrocca@uxdivers.com with your order number and the project so I can take a look?

Thanks,
JP

**Comment by Goldstrike** [comment] 2017-09-12 05:50
The `Xamarin.Android.* `packages version is `v25.4.0.2`
I will send you an email.

**Comment by jpbrocca** [comment] 2017-11-09 11:55
Hi @Goldstrike,
I sent you by email with my results running your project and the issue could not be reproduced.
I am closing this issue now but feel free to reopen if needed.

Best
JP

**Closed by jpbrocca** 2017-11-09 11:55 UTC
