### ISSUE TITLE
Menu Hamburger Icon disappears on pre-iOS12

### ISSUE THREAD

**Issue by GeorgeFromDallas** [UXDivers/Grial-UI-Kit-Support#629] opened 2019-10-03 02:10 UTC
The menu's Hamburger icon on iOS10 or iOS11 devices disappears after the first view load.

I can still click on the area where the icon is supposed to be, but it is not visible.

It works fine on iOS12 and iOS13.

I have tested on the base Grial V3 Pro solution download and the problem exists.

### Steps to Reproduce
1.  Open Grial v3 Pro App on iPhone Simulator using iOS10 or iOS11.
2.  Click on Menu Hamburger Icon and select any menu item.
3.  Notice the Hamburger icon in upper left corner disappears and never returns

### Expected Behavior
Icon should remain visible when navigating views.  (Just like iOS12 and iOS13)

### Actual Behavior
Menu Hamburger Icon disappears in iOS10 and iOS11

### Basic Information
- Version with issue:  v3 Pro (UXDivers.Grial v3.0.46) 
- Last known good version: ?
- IDE: Visual Studio 2019 Pro on PC
- Platform Target Frameworks: 
  - iOS:  Deplolyment Target 10.0

- Nuget Packages:  Standard as download.  *ALSO tested with UXDivers.Grial v3.0.51-RC nuget, but problem still exists
- Affected Devices:
iPhone 8, X, 11 (Plus / Max also same behavior)

Affected OS: iOS 10.3 and iOS 11

### First Page Load (looks ok)
![First-Page-Menu-Hamburger](https://user-images.githubusercontent.com/35197710/66094096-5eb03600-e558-11e9-96f3-62190051546c.png)

### Selecting Menu Item 
![Selecting-Menu-Item](https://user-images.githubusercontent.com/35197710/66094279-0c234980-e559-11e9-8f49-15c0f23e55b6.png)

### After Selecting Menu Item Icon Disappears
![Missing-Menu-Hamburger](https://user-images.githubusercontent.com/35197710/66094105-6243bd00-e558-11e9-9083-2558327e9cce.png)

**Comment by GeorgeFromDallas** [comment] 2019-10-03 02:23
FYI: I also tried changing the Page.**Icon** property in the xaml to use the recommended  Page.**IconImageSource** property, but it doesn't help.  

I did this due the **Icon** property being flagged as [Obsolete by Microsoft](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.icon?view=xamarin-forms).

Forms Project:
File:   /Views/DemoApp/MainMenuPage.xaml

```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:grial="clr-namespace:UXDivers.Grial;assembly=UXDivers.Grial" xmlns:local="clr-namespace:ProjectName"
	x:Class="ProjectName.MainMenuPage"
	NavigationPage.HasNavigationBar="false"
	Icon="{ StaticResource HamburguerIcon }"
	Style="{ StaticResource MainMenuStyle }"
	Title="{ grial:Translate PageTitleMainMenu }">

```

**Per Xamarin.Forms [documentation](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.page.icon?view=xamarin-forms)**
![Page Icon-Obsolete](https://user-images.githubusercontent.com/35197710/66094599-31648780-e55a-11e9-9325-20c0371cd57d.png)

**Comment by dirivero** [comment] 2019-10-04 17:20
Thanks for the comment on the obsolete property, I will update that in Grial.

I was not able to reproduce the problem you mentioned tough. Tried with a clean downloaded solution with iOS 11.4 with iPhone X, SE and 8.

![image](https://user-images.githubusercontent.com/7670773/66226342-edd06180-e6b0-11e9-9c69-a5076da48956.png)

The hamburguer icon stays even after using the master detail options.

Do you have latest xamarin/xamarin.iOS/Xcode?

**Comment by dirivero** [comment] 2019-10-04 17:21
Also, does this happen in physical devices?

**Comment by dirivero** [comment] 2019-12-04 14:45
I'm going to close this issue as we didn't get more information. Feel free to contact us again if the problem persist.

**Closed by dirivero** 2019-12-04 14:45 UTC
