### ISSUE TITLE
Custom NavBar is not replacing the standard one in Android

### ISSUE THREAD

**Issue by alberto175** [UXDivers/Grial-UI-Kit-Support#24] opened 2016-03-14 09:10 UTC
In Android, I see two NavBars instead of one. See the screenshot below. 
In iOS, the custom NavBar is working correctly.

GrialKit 1.2.1

Any suggestion? I need to show only 1 custom navbar of course

Thanks

![2016-03-14 10_08_54-](https://cloud.githubusercontent.com/assets/17824489/13739677/d7e2c424-e9cc-11e5-9cde-b50c08bf3207.png)

**Comment by jpbrocca** [comment] 2016-03-14 09:33
Hi @alberto175.

Did you made this page or this is the one from the provided sample with Grial?
If it is your page, then please take a look at our sample app.
This page should be modal in order to not to show the native NavBar.

Regards,
JP

**Comment by alberto175** [comment] 2016-03-14 09:46
This is from your sample, I've just run the sample project as is

Thanks
--Alberto

**Comment by jpbrocca** [comment] 2016-03-14 10:15
That is supposed to show you only the custom NavBar.

Did you make an update to packages maybe?
Which device are you testing with and which Android version it uses?

Thanks,
JP

**Comment by alberto175** [comment] 2016-03-14 10:24
The same steps on iOS simulator bring to the correct result (open source code, compile, deploy).

I've opened the source code and Xamarin has restored the packages as usual. I can reproduce the bug on simulators and real devices:

- Xamarin Player's Nexus 4 Android API 23 (Marshmallow)
- Xamarin Player's Nexus 4 Android API 19 (Kit Kat)
- Tested the demo APK from the Grialkit website on an old Samsung S3 mini (API 16). Same bug. I know API 16 is not supported, but it is almost working :-)

**Comment by jpbrocca** [comment] 2016-03-14 13:28
Thanks for the details.
I am testing here and I cannot reproduce your issue.
One more question: which is the xamarin forms package version that is installed on your project?

**Comment by alberto175** [comment] 2016-03-14 13:46
It is XF 2.0.0.6490

I have upgraded to 2.1.0.6529, but then Grial.Droid doesn't compile anymore and gives me 2 errors:

> \samples\Grial\Droid\Resources\Resource.designer.cs(115,115): Error CS0117: 'UXDivers.Artina.Grial.Resource.String' does not contain a definition for 'ApplicationName' (CS0117) (Grial.Droid)
> 
> \samples\Grial\Droid\Resources\Resource.designer.cs(105,105): Error CS0117: 'UXDivers.Artina.Grial.Resource.String' does not contain a definition for 'Hello' (CS0117) (Grial.Droid)
> 

Not sure if it's related to http://forums.xamarin.com/discussion/57283/unable-to-find-a-version-of-xf-compatible-with/p2

**Comment by jpbrocca** [comment] 2016-03-14 14:52
Well, I just wanted to be sure you were on 2.0.0.*.
I was suspecting you accidentally updated to 2.1 and that could be the reason of a "breaking change".

Try to restore to 2.0.0*

I will investigate more but there is something with your Android project for sure.

**Comment by jpbrocca** [comment] 2016-07-18 16:47
closing this isssue since it is fixed on Grial 1.5

**Closed by jpbrocca** 2016-07-18 16:47 UTC
