### ISSUE TITLE
TabControl onOrientationChanged with ListView doesn't change size back

### ISSUE THREAD

**Issue by Nietoperek** [UXDivers/Grial-UI-Kit-Support#315] opened 2017-11-17 15:11 UTC
When I rotate phone portrait->landscape it expands and works fine, but when I want want to rotate phone back(portrait -> landscape -> portrait) it doesn't shrink TabControl back. 
It seems to be issue with ListView(tested with buttons and it works).

**Comment by jpbrocca** [comment] 2017-11-17 15:46
Hi @Nietoperek,
Can you provide more details such as:

- Grial version and if it is Grial PRO RTL or not.
- Xamarin Forms version you are using
- Is this happening on iOS, Android or both? 
- Are you testing on real devices or emulators? Which versions?
- Can you put some schematic representation of your page so I can take a look?
  - Something like:
    ~~~
        <ContentPage.Content>
            <tab:TabControl>
                <tab:TabItem Text="Main">
                    <ListView .. />
                </tab:TabItem>
                <tab:TabItem Text="Second">
                    <Label .. />
                </tab:TabItem>
            </tab:TabControl>
        <ContentPage.Content>
    ~~~

Thanks,
JP

**Comment by Nietoperek** [comment] 2017-11-17 16:50
1. 2.5.2 Grial Pro
2. Xamarin.Forms 2.4.0.38779
3. Probably just Android, works on iPhone 5.
4. Real devices, Android 7.0, Android 6.0, iOS 9.3.2
5.  As follows:
<Grid x:Name="PageLayout" RowSpacing="0">
{...}
<RelativeLayout x:Name="ContentHolder" Grid.Row="1"  HorizontalOptions="Fill" VerticalOptions="Fill" Style="{ StaticResource ContentStyle }">
                <StackLayout x:Name="BackgroundHolder"
                            RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1, Constant=0}"
                            RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1, Constant=0}"/>
                <StackLayout x:Name="BackgroundMenuHolder"
                            RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1, Constant=-48}" 
                            RelativeLayout.HeightConstraint="48"
                            RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1, Constant=0}"/>
                <tab:TabControl x:Name="tabControl" TabStripPlacement="Bottom" Padding="0" StyleClass="iOSTabControlStyle" BackgroundColor="Transparent"
                            RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=1, Constant=0}"
                            RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=1, Constant=0}">
                    <tab:TabItem x:Name="tabHome" Text="{ local:Translate TabHome }" Icon="ic_home_white" IconSelected="ic_home_white" >
                        <controls:CategoryList x:Name="categoryList" />
                    </tab:TabItem>
                    <tab:TabItem x:Name="tabNotification" Text="{ local:Translate TabNotifications }" Icon="ic_notifications_white" IconSelected="ic_notifications_white">
                        <RelativeLayout x:Name="secondTabContent" Style="{ StaticResource ContentStyle }">
                        </RelativeLayout>
                    </tab:TabItem>
                    <tab:TabItem x:Name="tabSettings" Text="{ local:Translate TabSettings }" Icon="ic_settings_white" IconSelected="ic_settings_white">
                        <StackLayout Spacing="24" x:Name="thirdTabContent" Padding="24,24,24,0" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                            <StackLayout HeightRequest="60" Orientation="Horizontal" HorizontalOptions="FillAndExpand"
                                BackgroundColor="{ x:Static local:ThemeHelper.PrimaryColor }">
                                <Label Margin="24,0,0,0" {...}
                                    HorizontalOptions="StartAndExpand" VerticalOptions="Center"/>
                                    {...}
                            </StackLayout>
                            <Button HeightRequest="60" {...} />
                            <Button HeightRequest="60" {...}  />
                        </StackLayout>
                    </tab:TabItem>
                </tab:TabControl>
            </RelativeLayout>
        </Grid>

Tab3(tabSettings) works fine, but Tab1(tabHome) doesn't with ListView(tested with custom data template and with default and even empty list).

**Comment by jpbrocca** [comment] 2017-11-17 19:43
Hi @Nietoperek,
It seems there are some styles and controls that are needed to better understand what is going on.

A few comments:

- Is there any chance you could send me the full code to 
![image](https://user-images.githubusercontent.com/15996999/32965658-ec3bd3e4-cbb5-11e7-87f0-7417c6837a30.png) ?
- If not possible, could you send me a video showing your current result?
- I would like to better understand your layout requirements, but at first, it seems a little bit complex (and that could be potentially causing this issue, meaning you could achieve the same result with a safer layout).
- What is the `<controls:CategoryList x:Name="categoryList" />`...just a `ListView` or it is a composition with some layout?

Regards and thanks,
JP

**Comment by jpbrocca** [comment] 2017-11-17 19:49
One last comment:

What happens if you replace: 
~~~
<controls:CategoryList>
~~~
...with some basic element such as:
~~~
<BoxView BackgroundColor="Aqua"/>
~~~
..do you still get the same issue?

**Comment by Nietoperek** [comment] 2017-11-17 20:25
I didn't try with boxview, but If I replace it with code from tabSettings(some nested stack layouts with buttons and labels) it works fine... CategoryList is ListView  with header and datatemplates. But I tested it without datatemplates(plain ListView with header) and it had the same effect. My RelativeLayout resizes but tabControl doesn't shrink and it allows to scroll horizontally.
I'm unable to give you more information than this untill Monday.

**Comment by Nietoperek** [comment] 2017-11-20 09:54
I put simple ListView in tab:TabItem and it works the same - as described in first comment.
            <ListView x:Name="ItemsListView"
                RowHeight="80">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                                <StackLayout VerticalOptions="Center">
                                    <Label Text="Test" Style="{DynamicResource ListItemTextStyle}"/>
                                    <Label Text="Test2" Style="{DynamicResource ListItemDetailTextStyle}"/>
                                </StackLayout>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>

**Comment by jpbrocca** [comment] 2017-11-21 17:24
Hi @Nietoperek, how are you?

I tested with your code and couldn't reproduce your issue.
Although I had to add some styles to make it work (i.e.:`ListItemTextStyle`, `ListItemDetailTextStyle`, etc.).
Could be possible that those styles could be causing some issues, but I don't know for sure because I don't have such styles.

If you want you can send me your files to the email mentioned above, or I can reply your mail with my test page so you can take a look if you get the same results as I get.

Best,
JP

**Comment by jpbrocca** [comment] 2017-12-11 10:55
Closing this to keep things tidy. Feel free to reopen as needed.

**Closed by jpbrocca** 2017-12-11 10:55 UTC
