### ISSUE TITLE
GridOptionsView Xamarinforms

### ISSUE THREAD

**Issue by CharanDarbasthu** [UXDivers/Grial-UI-Kit-Support#448] opened 2018-07-10 10:48 UTC
Hello im using GridoptionsView for a UI like it contains couple of items(2*n) and here the issue is when the grid is having only four items it is scolling irrespectively and it is occuping full(FillAndExpand) area in the scrollview. I don't want to scroll the grid when it perfectly fits the screen.

Thanks in advance!

**Comment by CharanDarbasthu** [comment] 2018-07-10 10:53
Im using
.Net Standard 2.0
Xamarin forms version-3.1.0  
Grial UI kit version-2.6.9

**Comment by LeoHere** [comment] 2018-07-11 21:21
@CharanDarbasthu can you attach a screenshot and the piece of XAML where you instantiate the `GridOptionsView` ?

**Comment by mirogrg1** [comment] 2018-09-18 04:15
I think I have the same issue but only for Android. XAML for GridOptionsView 

`   <controls:PullToRefreshLayout
              Grid.Row="0"
              x:Name="pullToRefreshLayout"
              IsPullToRefreshEnabled="True"
              RefreshCommand="{Binding RefreshCommand}"
              IsRefreshing="{Binding IsBusy}">
                <ScrollView VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                    <artina:GridOptionsView                           
                         x:Name="ListUsers"               
			            ColumnCount="3"
                        RowCount="5"
			            BackgroundColor="White"
			            ColumnSpacing="0"
			            RowSpacing="0"
			            Padding="0"          
			            VerticalOptions="StartAndExpand"
			            ItemsSource="{Binding Users}" >
                        <artina:GridOptionsView.ItemTemplate>
                            <DataTemplate>
                                <local:DashboardItemTemplate   
						            ShowBackgroundImage="true"
						            ShowBackgroundColor="false"                       
						            ShowiconColoredCircleBackground="false"					
						            TextColor="{ DynamicResource OverImageTextColor }"                                    
                                    />
                            </DataTemplate>
                        </artina:GridOptionsView.ItemTemplate>
                    </artina:GridOptionsView>
                </ScrollView>
            </controls:PullToRefreshLayout>`


Screenshot:

![screenshot_1537244031](https://user-images.githubusercontent.com/17731204/45664057-86f50000-bacf-11e8-8bdc-5546095a332f.png)

**Comment by jpbrocca** [comment] 2018-09-18 09:42
Hi @mirogrg1,

I think the problem is caused because you are including the `GridOptionsView` inside a `ScrollView`.
This layout control will need the specific width and height of each item in this context to render properly.
Check `DashboardScrollablePage.xaml` for a sample.

Hope that helps,
JP

**Comment by mirogrg1** [comment] 2018-09-18 16:02
I see. Yeah, I might end up having to use the DashboardScrollablePage. Thanks for quick response!

**Comment by jpbrocca** [comment] 2018-09-18 18:10
You are welcome!
I am closing this issue now to keep things tidy, feel free to reopen it if necessary.

Best,
JP

**Closed by jpbrocca** 2018-09-18 18:10 UTC
