### ISSUE TITLE
uxdivers.artina.shared.licenseException

### ISSUE THREAD

**Issue by Samirnasrallah** [UXDivers/Grial-UI-Kit-Support#646] opened 2019-11-18 14:24 UTC
how to solve this error? 

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by LeoHere** [comment] 2019-11-18 15:41
@Samirnasrallah The root cause of this problem is described in the Exception's message and stack trace. Can you please provide the full stack trace?

**Comment by dirivero** [comment] 2019-12-04 14:42
I'm going to close this issue as we didn't get more information. Feel free to contact us again.

**Closed by dirivero** 2019-12-04 14:42 UTC
