### ISSUE TITLE
Design time doesn't work for preview pages, error related license

### ISSUE THREAD

**Issue by goodlogin** [UXDivers/Grial-UI-Kit-Support#446] opened 2018-06-25 18:08 UTC
How to resolve this issue?
<img width="791" alt="screenshot at jun 25 21-07-21_designtime" src="https://user-images.githubusercontent.com/3664393/41867433-cff95306-78bb-11e8-8378-bd69aac12b96.png">

**Comment by jpbrocca** [comment] 2018-06-25 21:04
Hi @goodlogin,

This is a duplicate of:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/348

The Xamarin Previewer has some limitations.
I suggest you try with Gorilla Player and Gorilla SDK which will allow you to preview Grial without issues. 

Please check the Grial docs about it:
http://uxdivers.github.io/Grial-UI-Kit-Support/docs.html#grial-uikit-overview-previewing-grial-with-gorilla-player

You can download your Grial Full or Starter projects from Grial Admin with Gorilla SDK preconfigured.

Best,
JP

**Closed by jpbrocca** 2018-06-25 21:04 UTC
Labels: duplicate

**Comment by goodlogin** [comment] 2018-06-26 05:46
But I dont want to use Gorilla Player and Gorilla SDK, I want to use DesignTime Previewer only.
Are there any solution to help me use DesignTime Previewer with Grial UI Kit?
Regards,
Andrew

**Comment by LeoHere** [comment] 2018-06-26 23:09
@goodlogin, Grial shared nuget packages version `2.7.5` (just released) play nicer with the Xamarin Previewer limitations. The issue you mentioned will not happen any more. By upgrading to `2.7.5` you will be able to preview a big part of Grial. There are still some things you will not be able to preview, but are related to other limitations of the Xamarin Previewer that hopefully will be overcame as it matures. 

We strongly recommend using Gorilla Player to have a better preview experience of Grial.

**Comment by IoTFier** [comment] 2019-03-01 08:38
Hi @LeoHere , how are you? In VS 2019 RC, I upgraded UXDivers.Artina packages to 2.7.6-RC with Xamarin.Forms 4.0 pre5. But the DesignTime Previewer is throwing following error -
Can you help me to resolve this error ? Thanks

![xaml-previewer-error vs2019](https://user-images.githubusercontent.com/26844611/53626328-07657400-3bcb-11e9-994c-1f51a17e0fd4.JPG)

**Comment by LeoHere** [comment] 2019-03-01 22:08
@IoTFier not sure how to help you there. It looks like a limitation of the XAML previewer...

**Comment by IoTFier** [comment] 2019-03-01 23:14
@LeoHere, It seems that the error is thrown while parsing xml that describes (may be metadata ?) constants or static members of GrialShapesFont ? Can someone on GrialKit team debug the issue ?

I would appreciate your help. 
Thanks
