### ISSUE TITLE
Everytime I close the app "an unhandled exception occured. "

### ISSUE THREAD

**Issue by shengguow** [UXDivers/Grial-UI-Kit-Support#184] opened 2017-05-25 16:06 UTC
The app successfully start up and run perfectly, but if I close it an unknown exception throws.
To reproduce the issue, just download an new sample from my account, open it and run the Android project. Is it because that I ever changed app name or package name? (but I successfully start up the app, so the license and configurations should be right.) 

Or you can download my project via this link to reproduce the issue.
(I mailed the download link of my project to your personal email, please check that)

My environment:
Visual studio community 2017
Lastest Grial UI kit
I tested on Android 6.0 emulator and Samsung Galaxy S7 with Android 7.0,
both of them have same issue.

Please  help to solve it.

**Comment by jpbrocca** [comment] 2017-05-25 18:30
Hi @shengguow, how are you?
This is caused by a known bug from Xamarin:
https://bugzilla.xamarin.com/show_bug.cgi?id=46494

I have replied your email with a workaround for this issue.

Best,
JP

**Comment by shengguow** [comment] 2017-05-26 01:16
Hello @jpbrocca ,
Thanks for the solution!
You'r right! Xamarin Forms seems feature-rich but not bug-free,
Your code also explained why my Xamarin project did not stop even I closed my app via the back button pressed. I need to stop the application manually.

(BTW,I thought bugs are fixed after I upgraded my Xamarin Form, no crashes, but actually the app did not be released, so I have to release manually.)

**Comment by shengguow** [comment] 2017-05-26 01:31
Fixes #184.

**Comment by shengguow** [comment] 2017-05-26 01:52
Hello @jpbrocca ,
I can't close the issue, I don't find a Mark as close option, please help to close it.
Thanks!

**Comment by jpbrocca** [comment] 2017-05-26 03:09
Hi @shengguow,
Thanks for the update and I am glad it worked.

I am closing this issue now.

Best,
JP

**Closed by jpbrocca** 2017-05-26 03:09 UTC

**Comment by johncdoherty** [comment] 2017-05-27 02:34
@jpbrocca, can you share this workaround with the rest of us? 
Thanks, 
John

**Comment by shengguow** [comment] 2017-05-27 03:53
For your reference:

                public override void OnBackPressed()
		{
			var app = Xamarin.Forms.Application.Current as App;

			if (app != null)
			{
				var mainPage = app.MainPage as MasterDetailPage;
				var navStackCount = mainPage.Detail.Navigation.NavigationStack.Count;
				var modalStackCount = mainPage.Navigation.ModalStack.Count;

				if (navStackCount > 1 || modalStackCount != 0)
				{
					base.OnBackPressed();
				}
				else
				{
					Android.OS.Process.KillProcess(Android.OS.Process.MyPid());
				}
			}
		}

        //// Workaround for
        //// JniEnvironment+InstanceMethods.CallIntMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method)
        //// http://stackoverflow.com/questions/7575921/illegalstateexception-can-not-perform-this-action-after-onsaveinstancestate-wit
        protected override void OnSaveInstanceState(Bundle outState)
        {
            //No call for super(). Bug on API Level > 11.
        }

**Comment by shengguow** [comment] 2017-05-27 15:38
I found the other workaround, just simply kill the process:
protected override void OnDestroy()
{
      // base.OnDestroy();
      Android.OS.Process.KillProcess(Android.OS.Process.MyPid());
}
