### ISSUE TITLE
Android ContextAction display issue

### ISSUE THREAD

**Issue by pboisso** [UXDivers/Grial-UI-Kit-Support#183] opened 2017-05-24 14:44 UTC
In the Message screen, when using ContextAction, the status bar is messed up with the ContextMenu.  Any workaround for this?

**Comment by jpbrocca** [comment] 2017-05-25 03:51
Hi Patrice, how are you?

Can you add more details?...is this happening on iOS, Android or both?
Could you paste a screenshot?

Regards and thanks,
JP

**Comment by pboisso** [comment] 2017-05-25 14:53
Doing great, thanks ! Here is the screenshot from Grial 2.0 on Android.  See how the status bar is hidden and how a black stripe appears below the Action bar.

![c0c50f45-4caf-4c66-b277-0d0f76959032](https://cloud.githubusercontent.com/assets/233448/26455473/51382fc6-4138-11e7-9db1-8829184ad9a7.png)

**Comment by jpbrocca** [comment] 2017-05-25 21:49
Hi @pboisso,

OK, thanks for the details. I confirm I can reproduce this issue.
I am investigating the cause and will get back to you as soon as I have a fix.

Best regards,
JP

**Comment by jpbrocca** [comment] 2017-05-26 13:27
Hi @pboisso, how are you?

To fix this issue you need edit to both `Style.xml` files on your Android project:

```
Grial
 |_ Grial.Droid
    |_ Resources
        |_ values
            |_ Style.xml
        |_ values-v21
            |_ Style.xml
```
...locate the `AppTheme` style:

```
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
     ...
</style>
```

...and add the following line inside the style:

`<item name="windowActionModeOverlay">true</item>`

You should see things as expected now:

![image](https://cloud.githubusercontent.com/assets/15996999/26496393/b9204e6e-41fd-11e7-8543-64f9f48adcc0.png)

Best,
JP

**Comment by pboisso** [comment] 2017-06-05 13:11
This working now, thanks for the quick fix !

**Comment by jpbrocca** [comment] 2017-06-05 17:03
Perfect!
Closing this issue now.
Best,
JP

**Closed by jpbrocca** 2017-06-05 17:03 UTC
