### ISSUE TITLE
Error generating license

### ISSUE THREAD

**Issue by wiltwitt** [UXDivers/Grial-UI-Kit-Support#162] opened 2017-04-09 01:40 UTC
I am trying to generate the starter and I get "Internal server error" message.
I have been fighting with this license issue for weeks now.  I just can't get it to work.  This is driving me nuts. I am at a point where I don't want to use this but get my money back.  Problem is that it never generates the way I entered.  I type in xxx.droid but it will generate as xxx.core for android.  What the hell...

https://uxdivers.com/secure/grial/api/v1/apps/37/download/starter

**Comment by wiltwitt** [comment] 2017-04-09 02:20
Will someone screen cast generating license through the admin portal and post it on youtube?

**Comment by LeoHere** [comment] 2017-04-09 13:18
@wiltwitt , I'm really sorry for all the inconvenience you have experienced. 

From the logs I can tell two things:
- At some point both the iOS and Android projects ends up with the same name. That was causing an issue when the package was generated.
- When that error occurs, there was a lock on the staging folder which did not allow you to generate the package again until the lock timed out 10 minutes after its creation.

You should be able to download the starter/full project now, since those locks have been released and projects have a different name now.

We will work on fixing two issues, in order to avoid anyone to experience this issue again:
- Ensure that all locks are correctly released when errors occurs
- Validate that projects have different names.

Again, sorry for the inconvenience and don't hesitate to contact us if you have any other issue.

**Comment by wiltwitt** [comment] 2017-04-09 15:53
one of my issue is that a generated project is using library namespace instead of droid or ios project namespace entered on admin portal.  this is driving me nuts.  Will you guys fix this bug ASAP?  I can't change my own droid and ios project namespace.  This is causing me bunch of errors.

**Comment by LeoHere** [comment] 2017-04-10 11:00
@wiltwitt as I mention in the other thread, we will address this ASAP. In the meantime, if you want to upgrade the namespaces by hand you will need to update the namespace declaration in:

**Android**
- ```MainActivity.cs```
- ```Properties/AssemblyInfo.cs```
- ```Renderers/CustomFontLabelRenderer.cs```

Additionally, change the default namespace of your Droid project.

**iOS**
- ```AppDelegate.cs```
- ```Main.cs```
- ```ThemeColors.cs```

Additionally, change the default namespace of your iOS project.

**Note**: That if you changed the default namespace in your Droid/iOS project you will need to change accordingly the name of the license you pass to the ```GrialKit.Init``` in the ```AppDelegate.cs``` and ```MainActivity.cs```.

**Comment by wiltwitt** [comment] 2017-04-12 01:58
Ok What you said here didn't work.  I can run fine on Android but not on ios.  It fails on license line.  What in the world do I have to do to get this to work.  It works while back at one point but not anymore.  I guess I will have to wait until you guys fix the admin console

**Comment by LeoHere** [comment] 2017-04-12 14:09
Are you getting a "Error reading license” error? If that is the case probably you changed the iOS project default namespace but did not update the ```AppDelegate.cs```, as mentioned in the note above.

If you give me more details about the error I can help you fix it

**Comment by wiltwitt** [comment] 2017-04-13 02:08
Just downloaded the new one but same error with reading license.  I am at a loss

**Comment by LeoHere** [comment] 2017-04-16 10:14
@wiltwitt we released the update ```2.0.52.0``` for Grial App and Nuget packages that includes the fix for the issue you have. Just go to the Admin site and download the app again. 

Please, let me know if you have any issue.

**Comment by jpbrocca** [comment] 2017-04-16 20:29
Hi @wiltwitt, how are you?

For more info about this fix, please check:
http://uxdivers.github.io/Grial-UI-Kit-Support/release-notes.html

Best,
JP

**Comment by wiltwitt** [comment] 2017-04-16 21:10
I just downloaded the new starter project and it throws errors.



Error The "FailOnError" parameter is not supported by the "PropagateThemeTask" task. Verify the parameter exists on the task, and it is a settable public instance property.

Error The "PropagateThemeTask" task could not be initialized with its input parameters.



I have not tried the license part yet

Thanks

________________________________

**Comment by jpbrocca** [comment] 2017-04-16 21:19
Hi @wiltwitt,

Did you change your app's Grial version number on Grial Admin and saved changes before downloading?

![image](https://cloud.githubusercontent.com/assets/15996999/25074440/112fb85c-22d1-11e7-8495-13c9f15235b8.png)

Best,
JP

**Comment by LeoHere** [comment] 2017-04-16 22:33
@wiltwitt the error you mentioned was reported [here](https://github.com/UXDivers/Grial-UI-Kit-Support/issues/170). However, the client that reported it confirmed it was not happening with ```2.0.52.0```. Nevertheless , I think this error might not be related to any specific version of Grial, but to VS getting confused with the different versions of the ```PropagateThemeTask ``` task. ```FailOnError``` parameter was introduced in the new version of the task. I think VS is trying to resolve ```2.0.52.0``` ```.target``` using the old ```2.0.35.0``` assembly that did not had the property, thus it complains. 

Can you please do as follows:
- Double check the sample you are testing depends on 2.0.52.0
- Do a clean in the solution
- Restart Visual Studio
- Rebuild

Please let me know the results.

**PD**: Regarding @jpbrocca  comment, there is no need to explicitly select ```2.0.52.0```. By default all apps have the **Stick to latest stable version** set. So, if you download the starter project today it should be base on ```2.0.52.0```.

**Comment by wiltwitt** [comment] 2017-04-16 22:36
yep, I downloaded twice but still errors.

![error](https://cloud.githubusercontent.com/assets/721312/25074847/857fa544-22d3-11e7-9b08-4b6fe33eebfd.png)

**Comment by wiltwitt** [comment] 2017-04-16 23:37
Weird, Restarting VS worked for starter project.  Now I need to try this with my own project.

**Comment by LeoHere** [comment] 2017-04-17 00:34
@wiltwitt these kind of errors you were getting usually are related to nuget package restore problems...may be restarting VS trigger the restore package process again and succeeded...

**Comment by wiltwitt** [comment] 2017-04-17 02:33
well, that didn't work for my project.  I need to figure out why...

**Comment by wiltwitt** [comment] 2017-04-17 02:34
This license is just killing me.  I spent so much time just to get this to work.  Why do you guys do it this way.  Why can't it be just type the guid or something, I am going insane here.

**Comment by wiltwitt** [comment] 2017-04-17 02:37
now it fails for android and ios.  Ahhhhhhhhhhhhh

**Comment by wiltwitt** [comment] 2017-04-17 02:41
Ok guys, I am just going to give this another week and that's all.  I can't even work on my own code.

**Comment by LeoHere** [comment] 2017-04-17 10:52
@wiltwitt let's schedule a call so we can help you pass through these issues. Can you send me an email (to l r o d r i g u e z at uxdivers.com) with the time frame you are available for a call?

**Comment by wiltwitt** [comment] 2017-04-17 14:55
@LeoHere Thanks,  I will try again tonight and read the doc again.  If I fail then we can figure something out..  Thanks again

**Comment by wiltwitt** [comment] 2017-04-18 02:53
Wow, I finally got it to work but I am afraid when I change my the name and namespace for production, which I will, I will have to go through this again.  What a nightmare that was.

**Comment by wiltwitt** [comment] 2017-04-18 03:28
What is your money back policy by the way?

**Comment by LeoHere** [comment] 2018-03-03 10:20
Closing the issue. Feel free to reopen it if you need so.

**Closed by LeoHere** 2018-03-03 10:20 UTC

**Comment by dejobo** [comment] 2018-03-28 02:47
@LeoHere please help, I'm having the same issue. Thanks!

**Comment by JameelNabbo** [comment] 2018-11-28 23:59
Having same issue.

**Comment by LeoHere** [comment] 2018-11-29 10:32
@JameelNabbo please open a new issue (reference to this one if you need too) describing what is the issue you are experiencing specifically. There are several issues mentioned in this thread... thanks
