### ISSUE TITLE
Styling button like a switch

### ISSUE THREAD

**Issue by Altaf07Latheef** [UXDivers/Grial-UI-Kit-Support#247] opened 2017-09-18 16:52 UTC
How to select a single button from a pair and how can i change the style value of the button on click such that active button and disabled button have styles and interchanges styles when other button clicked? If i have given both styles in my app.xaml file.

**Comment by jpbrocca** [comment] 2017-09-18 17:57
Hi @Altaf07Latheef,

I guess the intended behavior can be achieved handling events on the buttons and performing style changes.

Since this is not an issue of Grial I am closing this thread.

Best,
JP

**Closed by jpbrocca** 2017-09-18 17:57 UTC
