### ISSUE TITLE
Problems with Resources

### ISSUE THREAD

**Issue by nijsf** [UXDivers/Grial-UI-Kit-Support#37] opened 2016-04-27 21:24 UTC
I have upgraded to the latest Forms (2.2.0.31), but doing so results in a large number of resources not being found in the Android project. Please advise how to resolve these issues. Your help is much appreciated.

Tool /Library/Frameworks/Xamarin.Android.framework/Versions/Current/bin/smcs execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/Wanderwatch.Parents.dll MainActivity.cs Resources/Resource.designer.cs Properties/AssemblyInfo.cs SplashActivity.cs Renderers/CustomFontLabelRenderer.cs Renderers/SignaturePadRenderer.cs Controls/SignaturePad_android.cs Targets/LogcatTarget.cs Helpers/Settings.cs Targets/ConsoleTarget.cs Targets/FastFileTarget.cs Targets/InMemoryBufferTarget.cs Targets/NullTarget.cs Targets/SyncFileTarget.cs Localization/Localize.cs /target:library /define:"DEBUG;__XAMARIN_ANDROID_v1_0__;__MOBILE__;__ANDROID__;__ANDROID_1__;__ANDROID_2__;__ANDROID_3__;__ANDROID_4__;__ANDROID_5__;__ANDROID_6__;__ANDROID_7__;__ANDROID_8__;__ANDROID_9__;__ANDROID_10__;__ANDROID_11__;__ANDROID_12__;__ANDROID_13__;__ANDROID_14__;__ANDROID_15__;__ANDROID_16__;__ANDROID_17__;__ANDROID_18__;__ANDROID_19__;__ANDROID_20__;__ANDROID_21__;__ANDROID_22__;__ANDROID_23__" /nostdlib /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/System.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/System.Xml.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v6.0/Mono.Android.dll /reference:../packages/Newtonsoft.Json.8.0.3/lib/portable-net40+sl5+wp80+win8+wpa81/Newtonsoft.Json.dll /reference:../lib/pcl/UXDivers.Artina.Shared.dll /reference:../lib/android/UXDivers.Artina.Shared.Droid.dll /reference:../packages/Xam.Plugins.Settings.2.1.0/lib/MonoAndroid10/Plugin.Settings.dll /reference:../packages/Xam.Plugins.Settings.2.1.0/lib/MonoAndroid10/Plugin.Settings.Abstractions.dll /reference:../packages/Splat.1.6.2/lib/monoandroid/Splat.dll /reference:../packages/Acr.Support.1.1.1/lib/MonoAndroid10/Acr.Support.Android.dll /reference:../packages/Xamarin.Android.Support.v4.23.3.0/lib/MonoAndroid403/Xamarin.Android.Support.v4.dll /reference:../packages/Xamarin.Android.Support.Vector.Drawable.23.3.0/lib/MonoAndroid403/Xamarin.Android.Support.Vector.Drawable.dll /reference:../packages/Xamarin.Android.Support.Animated.Vector.Drawable.23.3.0/lib/MonoAndroid403/Xamarin.Android.Support.Animated.Vector.Drawable.dll /reference:../packages/Xamarin.Android.Support.v7.AppCompat.23.3.0/lib/MonoAndroid403/Xamarin.Android.Support.v7.AppCompat.dll /reference:../packages/Xamarin.Android.Support.v7.RecyclerView.23.3.0/lib/MonoAndroid403/Xamarin.Android.Support.v7.RecyclerView.dll /reference:../packages/Xamarin.Android.Support.Design.23.3.0/lib/MonoAndroid43/Xamarin.Android.Support.Design.dll /reference:../packages/Xamarin.Android.Support.v7.CardView.23.3.0/lib/MonoAndroid403/Xamarin.Android.Support.v7.CardView.dll /reference:../packages/Xamarin.Android.Support.v7.MediaRouter.23.3.0/lib/MonoAndroid403/Xamarin.Android.Support.v7.MediaRouter.dll /reference:../packages/Xamarin.Forms.2.2.0.31/lib/MonoAndroid10/Xamarin.Forms.Platform.Android.dll /reference:../packages/Xamarin.Forms.2.2.0.31/lib/MonoAndroid10/FormsViewGroup.dll /reference:../packages/Xamarin.Forms.2.2.0.31/lib/MonoAndroid10/Xamarin.Forms.Core.dll /reference:../packages/Xamarin.Forms.2.2.0.31/lib/MonoAndroid10/Xamarin.Forms.Xaml.dll /reference:../packages/Xamarin.Forms.2.2.0.31/lib/MonoAndroid10/Xamarin.Forms.Platform.dll /reference:../packages/Acr.UserDialogs.4.3.4/lib/MonoAndroid10/Acr.UserDialogs.dll /reference:../packages/Acr.UserDialogs.4.3.4/lib/MonoAndroid10/Acr.UserDialogs.Interface.dll /reference:../packages/Acr.UserDialogs.4.3.4/lib/MonoAndroid10/AndHUD.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/System.Core.dll /reference:/Users/nijsa/CloudStation/WanderWatch/Android/Wanderwatch.Parents/Wanderwatch.Parents/bin/Debug//Wanderwatch.Parents.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/mscorlib.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Collections.Concurrent.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Collections.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.ComponentModel.Annotations.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.ComponentModel.EventBasedAsync.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.ComponentModel.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Diagnostics.Contracts.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Diagnostics.Debug.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Diagnostics.Tools.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Diagnostics.Tracing.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Dynamic.Runtime.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Globalization.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.IO.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Linq.Expressions.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Linq.Parallel.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Linq.Queryable.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Linq.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Net.NetworkInformation.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Net.Primitives.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Net.Requests.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.ObjectModel.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Reflection.Emit.ILGeneration.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Reflection.Emit.Lightweight.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Reflection.Emit.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Reflection.Extensions.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Reflection.Primitives.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Reflection.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Resources.ResourceManager.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.Extensions.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.InteropServices.WindowsRuntime.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.InteropServices.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.Numerics.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.Serialization.Json.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.Serialization.Primitives.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.Serialization.Xml.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Security.Principal.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.ServiceModel.Http.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.ServiceModel.Primitives.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.ServiceModel.Security.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Text.Encoding.Extensions.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Text.Encoding.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Text.RegularExpressions.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Threading.Tasks.Parallel.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Threading.Tasks.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Threading.Timer.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Threading.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Xml.ReaderWriter.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Xml.XDocument.dll /reference:/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Xml.XmlSerializer.dll /warn:4
Resources/Resource.designer.cs(29,107): error CS0117: `UXDivers.Artina.Grial.Resource' does not contain a definition for `Animation'
		Resources/Resource.designer.cs(19,23): (Location of the symbol related to previous error)
Resources/Resource.designer.cs(30,108): error CS0117: `UXDivers.Artina.Grial.Resource' does not contain a definition for `Animation'
		Resources/Resource.designer.cs(19,23): (Location of the symbol related to previous error)
Resources/Resource.designer.cs(31,124): error CS0117: `UXDivers.Artina.Grial.Resource' does not contain a definition for `Animation'
		Resources/Resource.designer.cs(19,23): (Location of the symbol related to previous error)
Resources/Resource.designer.cs(32,111): error CS0117: `UXDivers.Artina.Grial.Resource' does not contain a definition for `Animation'
		Resources/Resource.designer.cs(19,23): (Location of the symbol related to previous error)
Resources/Resource.designer.cs(33,110): error CS0117: `UXDivers.Artina.Grial.Resource' does not contain a definition for `Animation'
		Resources/Resource.designer.cs(19,23): (Location of the symbol related to previous error)
Resources/Resource.designer.cs(34,127): error CS0117: `UXDivers.Artina.Grial.Resource' does not contain a definition for `Animation'
		Resources/Resource.designer.cs(19,23): (Location of the symbol related to previous error)

I get this error 1539 times!

The IOS project compiles fine

**Comment by nijsf** [comment] 2016-04-27 21:30
Downgrading to Forms 2.0.0.6490 seems to resolve the issues, but I need a later version of Forms for other dependencies.

**Comment by giammin** [comment] 2016-04-28 15:03
very annoying. hope they resolve this quickly

**Comment by diego5** [comment] 2016-04-28 16:09
Hi,

I'm sorry for the inconvenience. This problem is caused by how Android resources are propagated between projects. I'm glad to tell you that we've included a workaround for this problem which we are currently testing and we plan to release very soon.

I'll let you know when is ready. 

Thanks for reporting the issue.

**Comment by nijsf** [comment] 2016-04-28 18:33
That's great to hear. Many thanks

**Comment by giammin** [comment] 2016-04-29 07:19
Awesome!

i don't know if it is related but after upgrading xamarin.forms to the latest version. I had on ios projects strange crashes which stopped happening after removing your custom renderes definitions

```csharp

// Custom renderer definition

[assembly: ExportRenderer(typeof(UXDivers.Artina.Shared.CircleImage), typeof(UXDivers.Artina.Shared.ImageCircleRenderer))]
[assembly: ExportRenderer(typeof(EntryCell), typeof(UXDivers.Artina.Shared.ArtinaEntryCellRenderer))]
[assembly: ExportRenderer(typeof(ImageCell), typeof(UXDivers.Artina.Shared.ArtinaImageCellRenderer))]
[assembly: ExportRenderer(typeof(SwitchCell), typeof(UXDivers.Artina.Shared.ArtinaSwitchCellRenderer))]
[assembly: ExportRenderer(typeof(TableView), typeof(UXDivers.Artina.Shared.ArtinaTableRenderer))]
[assembly: ExportRenderer(typeof(TextCell), typeof(UXDivers.Artina.Shared.ArtinaTextCellRenderer))]
[assembly: ExportRenderer(typeof(ViewCell), typeof(UXDivers.Artina.Shared.ArtinaViewCellRenderer))]

[assembly: ExportRenderer(typeof(Entry), typeof(UXDivers.Artina.Shared.ArtinaEntryRenderer))]

#pragma warning disable 219
internal static class WorkaroundLoadingCustomRenderersFromExternalAssemblies {
	static WorkaroundLoadingCustomRenderersFromExternalAssemblies()
	{
		var a = new UXDivers.Artina.Shared.ArtinaEntryRenderer();
	}
}
#pragma warning restore 219

```

**Comment by jbravobr** [comment] 2016-04-30 17:43
Any road map for fix Grial UI for the latest Xamarin Forms ??

**Comment by lafersousa** [comment] 2016-05-01 23:27
Any updates? Just purchased the toolkit but can't get it working due to this issue.

**Comment by izefler** [comment] 2016-05-03 14:49
Any prevision? I am also having the same problem.

**Comment by jpbrocca** [comment] 2016-05-03 14:54
Hi guys,
The update will be released tomorrow.

Thanks
JP

**Comment by izefler** [comment] 2016-05-03 19:47
Very good! Thank you.

**Comment by jbravobr** [comment] 2016-05-04 11:39
@jbrocca how this update will be released (or delivered)? BTW thanks man!! Awesome work!

**Comment by diego5** [comment] 2016-05-04 14:08
Hi @nijsf and @giammin.

Could you guys send me an email to jpbrocca@uxdivers.com with your order number so I can send you the link to download the update ?

For the rest of the people on this thread: guys you will be receiving an email with the link.

Regards and thanks,
JP

**Comment by giammin** [comment] 2016-05-04 14:22
Hi @diego5 will you release any soon a new version of Grial UIKIT with that update?

**Comment by diego5** [comment] 2016-05-04 14:27
Hi @giammin,
the update is ready and it addresses the issue on this thread.

Please, send an email to jpbrocca@uxdivers.com with your order number in order to get the link with the update.

Best

**Comment by jbravobr** [comment] 2016-05-04 17:03
@diego5 how can I use themes from AppCompat with the update ?

**Comment by noxe** [comment] 2016-05-09 16:24
any News on the update? on the xamarin component store there is still the old Version?

**Comment by jpbrocca** [comment] 2016-05-09 16:29
Hi @noxe, how are you?

Please send me an email to jpbrocca@uxdivers.com with your order number so I can send you the link to this update.

Best,
JP

**Comment by kunjal29** [comment] 2016-05-09 16:48
Hi @jpbrocca 

I had sent you an email with my order number last week but still haven't received any link.

Thanks!
Kunjal

**Comment by jpbrocca** [comment] 2016-05-09 18:56
Hi @kunjal29, sorry about that.
It seems I made a typo when introducing your email to get the link.

You should receive a new email in a few minutes more.

Thanks for letting me know and I apologize for this mistake.

Best,
JP

**Comment by deman4ik** [comment] 2016-05-09 19:53
Got updated lib but still have Resources error.

**Comment by jpbrocca** [comment] 2016-05-09 20:03
Hi @deman4ik,

can you provide more info about the errors you get? 
Which version of forms are you using?
Did you updated your project with the new dlls from the update, cleaned and rebuilt the solution?

**Comment by deman4ik** [comment] 2016-05-10 12:44
> C:\Users\deman\Source\Repos\TUPMobile\TUPMobile\TUPMobile.Droid\Resources\Resource.Designer.cs(220,136,220,162): error CS0117: 'Resource.Attribute' does not contain a definition for 'mediaRouteSettingsDrawable'
> 3>C:\Users\deman\Source\Repos\TUPMobile\TUPMobile\TUPMobile.Droid\Resources\Resource.Designer.cs(369,130,369,158): error CS0117: 'Resource.Color' does not contain a definition for 'design_textinput_error_color'
> 3>C:\Users\deman\Source\Repos\TUPMobile\TUPMobile\TUPMobile.Droid\Resources\Resource.Designer.cs(477,133,477,156): error CS0117: 'Resource.Dimension' does not contain a definition for 'design_fab_content_size'
...
I tried 2.2.0.31 and 2.3.0.38-pre2. I updated new dlls, made clean and rebuild.

**Comment by jbravobr** [comment] 2016-05-10 13:42
@deman4ik ,

did you updated Xamarin Forms to the last version too ?

**Comment by nijsf** [comment] 2016-05-10 19:33
I can confirm the issue of @deman4ik. IOS works fine, but Android still has some resource problem. I am currently using Forms 2.2.0.31 and get resource errors, 151 in total.

**Comment by nijsf** [comment] 2016-05-10 19:37
I also ran the new sample project and that compiles (and runs) fine on Android.

**Comment by jpbrocca** [comment] 2016-05-10 19:38
Hi @deman4ik and @nijsf thanks for letting me know.
This is weird, from our samples/tests it seems to work. Also other guys who received the update didn't have any problems.
Thanks,
JP

**Comment by deman4ik** [comment] 2016-05-10 19:44
Not sure how is this related but finaly I made this work by fully deleting XamForms NuGet, removing refs to old Gorilla Players dlls, install XamForms NuGet again, Clean and Build Solution.
Thanks

**Comment by nijsf** [comment] 2016-05-10 20:00
My apologies. Upon closer inspection, it was not Grial causing the problems, but XLabs.Forms. I have removed the package from my Android project and now it compiles fine. Problem solved! Many thanks for the update.

**Closed** 2016-05-10 20:01 UTC

**Comment by jpbrocca** [comment] 2016-05-10 20:08
Hi @deman4ik and @nijsf thanks for letting us know.
Glad to know you can run Grial with no issues!

Thanks,
JP
