### ISSUE TITLE
Dashboard Multiple Tiles TapCommand Issue

### ISSUE THREAD

**Issue by wynerlim12** [UXDivers/Grial-UI-Kit-Support#598] opened 2019-07-14 07:30 UTC
Hi,
I'm new to Xamarin with Grial Ui Kit, I successful combine another slider to the dashboard tiles page, but now i'm facing some issue about the multiple tiles page navigation and icon. 
1) As below attach image, I wish to achieve each tiles can navigate to different page. For an example, I would like to do is when tap on "Member" will be navigate to webview "member" page with top nav button(Page with title and back button). 
2) And the icon, I try to put the value from the "GrialIconsFont" also didn't display like the Grial UI kit showing.

Hope to get references or solution from anyone which could assist me in order to solve issue. Appreciate on that!! 
![WhatsApp Image 2019-07-14 at 3 17 01 PM](https://user-images.githubusercontent.com/50734883/61180540-80310e00-a64a-11e9-904f-ff86a03fc149.jpeg)

**Comment by jpbrocca** [comment] 2019-07-22 20:01
Hi @wynerlim12, how are you?

about your questions:

1. Check the following links:
    - https://github.com/UXDivers/Grial-UI-Kit-Support/issues/207
    - https://github.com/UXDivers/Grial-UI-Kit-Support/issues/463
    - http://docs.grialkit.com/grid-view.html#working-with-the-gridview-samples-using-the-itemclickcommand
2. I am not sure where are you trying to put the icon, could you please add more details about what icon are you looking to use, where, and if this issue is happening when you are trying to preview your XAML or when you are running the app?

Best regards,
JP

**Comment by WilsonYHChan** [comment] 2019-08-19 07:49
Hi, JPBrocca:

refer to your answer 1.3, i have change to code as below:

 <ScrollView
		Orientation="Both">
        <grial:GridView
			WidthRequest="320"
			Margin="0"
			Padding="10"
			ColumnSpacing="10"
			RowSpacing="10"
			ItemsSource="{ Binding Items }"
            ItemClickCommand="{ Binding ItemCommand }"
            ItemTemplate="{ StaticResource Selector }"
            ColumnCount="2"/>
    </ScrollView>


using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Windows.Input;
using UXDivers.Grial;
using Xamarin.Forms;

namespace QlikApps
{
    public class DashboardMultipleTilesViewModel : ObservableObject
    {
        private readonly Command _itemCommand;
        public ICommand ItemCommand => _itemCommand;

        public DashboardMultipleTilesViewModel()
            : base(listenCultureChanges: true)
        {
            _itemCommand = new Command<DashboardMultipleTilesPage>(ItemAction);
            LoadData();
        }

        public ObservableCollection<DashboardMultipleTileItemData> Items { get; } = new ObservableCollection<DashboardMultipleTileItemData>();
        

        protected override void OnCultureChanged(CultureInfo culture)
        {
            LoadData();
        }

        private void LoadData()
        {
            Items.Clear();

            JsonHelper.Instance.LoadViewModel(this, source: "NavigationDashboards.json");
        
        }

        private void ItemAction(DashboardMultipleTilesPage items)
        {
           Application.Current.MainPage.DisplayAlert("Hello", items.Title, "OK");
        }

    }
}

but the ItemAction(DashboardMultipletilesPage item) not fire at all? 
please help.

**Comment by dirivero** [comment] 2019-10-05 20:00
This is a duplicate of https://github.com/UXDivers/Grial-UI-Kit-Support/issues/612
Please check the answer there.
Thanks!

**Closed** 2019-10-05 20:01 UTC
Labels: duplicate
