### ISSUE TITLE
How to handle `ItemTapped` on FrontPageNewsPage in Grial 2

### ISSUE THREAD

**Issue by Arul-** [UXDivers/Grial-UI-Kit-Support#180] opened 2017-05-19 03:39 UTC
We are trying to keep `FrontPageNewsPage` as the master page and handle clicks to navigate to a detail page

But `artina:GridOptionsView` does not seems to have an event for it. It seems to have `ItemClickCommand` property but there is no example on how to use it.

We tried couple of things but none worked so far

Please provide an usage example

**Comment by LeoHere** [comment] 2017-05-23 10:32
You can implement the intended behavior by:
1. using the ```ItemClickedCommand```.
2. attaching a ```TapGestureRecognizer``` to the ```FrontPageNewsItemTemplate```. Check the ```DasboardItemTemplate``` for an example of how to do this.


In order to use the ```ItemClickCommand``` property you need to:

1. Create the command object in the view model and expose it as a property. 

~~~
public class MyViewModel
{
	private readonly Command _itemCommand;

	public MyViewModel()
	{
		_itemCommand = new Command<MyItemType>(ItemAction);
	}

	public List<MyItemType> Items { ... }

	public ICommand ItemCommand => _itemCommand;

	private void ItemAction(MyItemType item)
	{
		// Action logic goes here...
	}
}
~~~

In the example, the property is called ```ItemCommand```.

2. Bind the ```ItemClickCommand``` to the command property (i.e. ```ItemCommand```)

~~~
<artina:GridOptionsView 
	ItemClickCommand="{Binding ItemCommand}"
	ItemsSource="{Binding Items}">
	<artina:GridOptionsView.ItemTemplate>
		<DataTemplate>
			...
		</DataTemplate>
	</artina:GridOptionsView.ItemTemplate>
</artina:GridOptionsView>
~~~

Please, notice that in the XAML the ```ItemClickCommand``` is defined before the ```ItemsSource``` property. If you define it the other way around, it will not work. This is a bug of the ```GridOptionsView```. It will be fixed in the next release.

**Comment by LeoHere** [comment] 2017-10-23 09:23
Closing this issue to keep things tidy. Please reopen if needed.

**Closed by LeoHere** 2017-10-23 09:23 UTC
