### ISSUE TITLE
Floating Action Button

### ISSUE THREAD

**Issue by webmasterdevlin** [UXDivers/Grial-UI-Kit-Support#306] opened 2017-11-06 17:16 UTC
Hi guys. Is there a floating action button that we can use in GrialUI?

**Comment by jpbrocca** [comment] 2017-11-09 11:28
Hi @webmasterdevlin,

If you are asking about a button that would stay fixed in your UI by itself, then the answer is no.
However, you can use in your page any of the button styles on Grial and use a `<Grid>` layout to make te button stay on the same row as your content.

Regards,
JP

**Comment by foswha** [comment] 2017-11-10 00:07
Could you provide an example in a lisview using a circular button? would be very helpful thanks

**Comment by webmasterdevlin** [comment] 2017-11-10 00:28
Here it is. The button that you usually see in emails or chat applications.
![unnamed](https://user-images.githubusercontent.com/22025912/32636761-1eed18a4-c5f1-11e7-81f4-728bfa072615.png)

**Comment by jpbrocca** [comment] 2017-11-13 18:59
Closing this issue now as it seems is not a bug.

Feel free to reopen if need.

Best,
JP

**Closed by jpbrocca** 2017-11-13 18:59 UTC
