### ISSUE TITLE
License validation error started occurring

### ISSUE THREAD

**Issue by james-lavery** [UXDivers/Grial-UI-Kit-Support#231] opened 2017-09-01 10:26 UTC
We're getting an error at runtime:

UXDivers.Artina.Shared.LicenseException: Internal license validation error

We haven't changed our licence, and as far as I am aware our licence was converted to 'Production' some time ago.

Versions:
UXDivers.Artina.Shared 2.0.52 
UXDivers.Artina.Shared.Base 2.0.52 

Should we update to 2.0.60 which is available from NuGet?

**Comment by LeoHere** [comment] 2017-09-01 10:46
Hi @james-lavery!

Usually the "Internal license validation error" has a inner exception which provides more details about the cause of the issue, can you double check the application output window to see if it is there?

When did you started seeing this error? In which context are you getting this error (debugging?)? Android or iOS? or both?

**Comment by james-lavery** [comment] 2017-09-01 10:49
Hi Leo,
Good point - I'll send the inner exception details shortly.

This has only just started happening - this is when running a debug build on a physical device, on Android.

**Comment by james-lavery** [comment] 2017-09-01 10:54
Full exception details:

> In mgmain JNI_OnLoad
> 09-01 11:51:39.353 E/mono-rt ( 5167): [ERROR] FATAL UNHANDLED EXCEPTION: UXDivers.Artina.Shared.LicenseException: Internal license validation error. ---> Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type UXDivers.Artina.Shared.Licensing.License. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'ClientId', line 1, position 12.
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract objectContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id, System.Boolean& createdFromNonDefaultCreator) [0x000d6] in <17a8e16c05e74b30a59389dcb721d998>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0013f] in <17a8e16c05e74b30a59389dcb721d998>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <17a8e16c05e74b30a59389dcb721d998>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <17a8e16c05e74b30a59389dcb721d998>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <17a8e16c05e74b30a59389dcb721d998>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <17a8e16c05e74b30a59389dcb721d998>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <17a8e16c05e74b30a59389dcb721d998>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at Newtonsoft.Json.JsonConvert.DeserializeObject[T] (System.String value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <17a8e16c05e74b30a59389dcb721d998>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at UXDivers.Artina.Shared.Licensing.LicenseManager.ValidateLicence (System.String license, UXDivers.Artina.Shared.Licensing.License& licenseObject, System.String& cause) [0x00139] in <af3b07b48b2b47cab84c155a7e91418c>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at UXDivers.Artina.Shared.Licensing.LicenseManager.Init (Android.App.Activity activity, System.String license, System.String& cause) [0x0001a] in <af3b07b48b2b47cab84c155a7e91418c>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):   at UXDivers.Artina.Shared.License.Init (Android.App.Activity activity, System.Reflection.Assembly assembly, System.String resourceName) [0x0005a] in <af3b07b48b2b47cab84c155a7e91418c>:0 
> 09-01 11:51:39.353 E/mono-rt ( 5167):    --- End of inner exception stack trace ---

**Comment by LeoHere** [comment] 2017-09-01 11:05
What version of `Newtonsoft.Json` are you using?

Does it happens on the simulator too?

**Comment by james-lavery** [comment] 2017-09-01 11:08
Newtonsoft 10.0.2

We haven't tried a simulator, we really need to use a physical device for this app.

**Comment by LeoHere** [comment] 2017-09-01 11:35
How is you linker configured in Android when building for this device?

**Comment by james-lavery** [comment] 2017-09-01 11:55
Hi Leo - I'll check in a minute (it's my colleague who's seeing the problem).

However, strangely if we do a Release build, the app works!

**Comment by james-lavery** [comment] 2017-09-01 15:20
It's set to link SDK and User Assemblies. I've tried setting to SDK only. I'll let you know if that makes a difference.

**Comment by james-lavery** [comment] 2017-09-01 15:30
No, setting to Link SDK assemblies only didn't fix it.

**Comment by LeoHere** [comment] 2017-09-01 16:51
@james-lavery, just in case, did you do  
+ clean/rebuild
+ manually remove the app from the device
+ deploy it again in order to test it

after you changed the linker settings?

**Comment by LeoHere** [comment] 2017-09-04 20:19
@james-lavery, any update on this?

**Comment by james-lavery** [comment] 2017-09-04 20:45
Hi Leo,
Thanks for the reminder. I think it has resolved itself after doing a full clean and rebuild.

Regards,
James Lavery
Managing and Technical Director
[cid:image013.jpg@01D325C7.104B8260]<http://www.microsec.co.uk/>

Tel:      +44 (0)23 9251 8252 (DDI)
+44 (0)7729 840551 (mobile)
Email:  james.lavery@microsec.co.uk<mailto:james.lavery@microsec.co.uk>
Web:   www.microsec.co.uk
[cid:image005.png@01D13356.2FDB99E0]<https://www.linkedin.com/in/james-lavery-1a785a1>

Microsec Ltd is a limited company registered in England and Wales. Registered number: 1462783. Registered office: Langstone Technology Park, Langstone Road, Havant, PO9 1SA

[cid:image001.png@01D03AD4.46684260]<https://xamarin.com/>  [cid:image009.jpg@01D03B07.4F924420] <http://www.tickitplus.org/certification/certified-organisations.aspx>   [cid:image011.jpg@01D03B07.4F924420] <http://www.tickitplus.org/certification/certified-organisations.aspx>   [cid:image004.png@01D04F6E.BA3B4DF0] <http://www.tickitplus.org/certification/certified-organisations.aspx>

**Comment by LeoHere** [comment] 2017-09-04 21:46
Ok, closing the issue. Open it if you find out the issue persisted.

**Closed by LeoHere** 2017-09-04 21:46 UTC

**Comment by sadranyi** [comment] 2018-02-18 17:14
we having similar issues @james-lavery  did you leave it at SDK only before doing a clean and full rebuild ?
