### ISSUE TITLE
Failed to retrieve information about 'UXDivers.Artina.Controls.Repeater' from remote source

### ISSUE THREAD

**Issue by juanmalm** [UXDivers/Grial-UI-Kit-Support#713] opened 2020-04-30 10:31 UTC
### Description
Hello gents,

Our builds just started to fail with this error:

[error]The nuget command failed with exit code(1) and error(Failed to retrieve information about 'UXDivers.Artina.Controls.Repeater' from remote source 'http://nuget.uxdivers.com/grial/FindPackagesById()?id='UXDivers.Artina.Controls.Repeater'&semVerLevel=2.0.0'.

Also trying to reach http://nuget.uxdivers.com/ I get this error:

![image](https://user-images.githubusercontent.com/22932620/80701027-0554b900-8adf-11ea-9e6d-4f1c29e1d95d.png)

### Steps to Reproduce
Just build

### Expected Behavior
Able to reach uxdivers

**Comment by LeoHere** [comment] 2020-04-30 11:01
@juanmalm there was an issue in one of our servers. It has been fixed now.

Please check again at your side and confirm the issue is gone.

Sorry for the inconvenience.

**Comment by juanmalm** [comment] 2020-04-30 11:33
worked!

**Closed** 2020-05-04 18:23 UTC
