### ISSUE TITLE
Error binding null

### ISSUE THREAD

**Issue by netoviskyy** [UXDivers/Grial-UI-Kit-Support#484] opened 2018-09-10 12:49 UTC
App crashes when call pages of grial layout

### Description
When I calls the LoginPage the application crashes, error "Value cannot be null. Parameter  name: binding"

### Expected Behavior
I need use the layout components for upgrade design of current app urgent.

### Basic Information
I followed all steps of documentation for add Grial to Existing Project, and pasted Full-Grial in my solution.

- IDE: VS 2017 15.8.2
-Xamarin Forms : 3.1.0.583944
-FFImageLoading : 2.4.3.840
-UXDivers Grial packages : 2.7.1
- Affected Devices: All devices

### Screenshots

![545](https://user-images.githubusercontent.com/36972630/45297969-71834300-b4dd-11e8-85a5-ab8917c8f9d9.png)

![xaml](https://user-images.githubusercontent.com/36972630/45298041-ad1e0d00-b4dd-11e8-94a2-5b73050adeec.png)

![987](https://user-images.githubusercontent.com/36972630/45298361-a643ca00-b4de-11e8-9472-2df0da63c28a.png)

**Comment by LeoHere** [comment] 2018-09-10 17:35
@netoviskyy thanks for all the provided information. I don't see any clear indication of what could be causing this error.

I guess that shearing the solution (privately) is not an option right?

Assuming it is not and in order to narrow the problem down, can you please start removing XAML pieces from the `LoginPage.xaml` until you can successfully push it (be sure to have a backup before proceeding). 
- Start by removing all the `artina:Translate` occurrences in the page. Just remove the whole property if possible or replace it with a random text.
- If it still crashes, remove all the `artina:OnOrientation*`. Just remove the property if possible or replace it with any of the values defined within the `artina:OnOrientation*`.
- If it still crashes, start removing chunks of the page's XAML until you find out what is causing the issue.

Please let me know you findings.

**Comment by netoviskyy** [comment] 2018-09-10 18:00
Ok, I will try

**Comment by netoviskyy** [comment] 2018-09-10 18:51
The LoginPage its worked. The problem was "artina:Translate". Now the question is why ? rsrsr

**Comment by LeoHere** [comment] 2018-09-11 11:56
@netoviskyy 

Do you have the following line in the `App.xaml.cs`?

~~~
public partial class App : Application
{
	public App()
	{
		InitializeComponent();

                 ...
		Resources["DefaultStringResources"] = new Resx.AppResources(); <---- THIS
                 ...
        }
}
~~~

I go through the [Adding Grial to an Existing Project](https://uxdivers.github.io/Grial-UI-Kit-Support/setup-grial-on-an-existing-project.html) guide and I don't see any mention of this. Probably because in the past this was done in the `App.xaml`, using XAML. But after moving to .NET Standard this needs to be done in the code behind.

Please check the `App.xaml.cs` of your starter or full project for more details on this.

Let me know your findings.

**Comment by netoviskyy** [comment] 2018-09-11 12:09
I added the line, but it still did not work

**Comment by LeoHere** [comment] 2018-09-11 12:18
@netoviskyy same exact error?

**Comment by netoviskyy** [comment] 2018-09-11 12:19
Yes, the same error.

**Comment by LeoHere** [comment] 2018-09-11 12:30
@netoviskyy I was able to reproduce your issue by commenting out the line i mentioned before.

![image](https://user-images.githubusercontent.com/16000584/45360111-fab17d00-b5a4-11e8-9db5-f0a00efd82c9.png)

Can you share the your `App.xaml.cs` just in case there is something different?

Also, can you try doing:
1. Full solution clean
2. Manually remove the app from the simulator or device
3. Rebuild and dedeploy of the app.

**Comment by netoviskyy** [comment] 2018-09-11 13:20
I'm testing on the android, both on the simulator and on the device. I tried this steps, but without success.
Can I send you print of my App.xaml.cs on particular?

**Comment by LeoHere** [comment] 2018-09-11 18:50
@netoviskyy yes write me to l r o d r i g u e z at uxdivers.com. Also send me the `MainActivity.cs`

**Comment by netoviskyy** [comment] 2018-09-12 11:56
ok, I sent you

**Comment by dirivero** [comment] 2019-04-12 22:56
I'm closing this issue as it was followed up by email.

**Closed by dirivero** 2019-04-12 22:56 UTC

**Comment by josemmp** [comment] 2020-03-13 18:28
I am having the same issue
![image](https://user-images.githubusercontent.com/34225481/76649346-16913880-6526-11ea-869a-99f72575df95.png)
