### ISSUE TITLE
Android fails to build Grial UI Kit v3

### ISSUE THREAD

**Issue by HomeroLara** [UXDivers/Grial-UI-Kit-Support#551] opened 2019-04-06 17:14 UTC
### Description
I'm currently using UI Kit v3.0 and the only project will not build is the Android platform project. I'm getting the following build errors from the MainActivity.cs:
- Reference.Style does not contain a definition for AppTheme: (this file exists)
- Reference.Layout does not contain a definition for Toolbar: (this file exists)
- Reference.Layout does not contain a definition for Tabbar: (this file exists)

I'm getting the following build errors from the ExtendedCarouselViewRenderer.cs:
- Reference.Id does not contain a definition for pager: this image is missing

*** The projects build successfully if I comment out the lines of code that reference these objects.

Also, I'm seeing the following reference missing from the Android project:
- System
- System.Core
- System.Xml
- System.Xml.Linq

Additionally, I'm seeing this for the Android build output:
- error MSB4018: The "LinkAssemblies" task failed unexpectedly

### Steps to Reproduce
Build the Android platform project 

### Basic Information
I'm currently using VS for Mac 19

Mono Framework MDK
Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

Xamarin.Android
Version: 9.2.0.5 (Visual Studio Enterprise)
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 29.0.0 rc2

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rafaelYstoc** [comment] 2019-04-08 13:08
I'm with the same problem.

**Comment by jpbrocca** [comment] 2019-04-08 18:10
Hello @HomeroLara and @rafaelYstoc,
We are investigating this issue.

Just a couple of questions to help us to find the root of this issue:
- Are you guys testing with a Grial Full or a Grial Starter solution?
- Are you using emulators or real devices?

Regards and thanks,
JP

**Comment by jpbrocca** [comment] 2019-04-08 18:12
Oh, I forgot to ask you guys:

- Are you using a Grial Standard or Grial Pro license?

Thanks!
JP

**Comment by jpbrocca** [comment] 2019-04-08 18:23
Hi again guys.

Even when we could not reproduce exactly your issue, we had similar issues and they happened when we tried to run the first time the downloaded solution.

Could you guys try with a "Clean" and "Rebuild"? In our case that was all.

If that won't help, another thing we noticed was that the `Resource.Designer.cs` won't regenerate, which is related to this issue in VS:
  https://developercommunity.visualstudio.com/content/problem/275112/resourcesdesignercs-code-behind-for-resx-file-not.html  

The main reason is that Visual Studio won’t regenerate the Resource.Designer.cs file in Android project. Then, it will complain and won’t let you run your app.

To fix this issue, simply try the following:

  1 - Close Visual Studio. 
2 - Locate the file `Resource.Designer.cs` in your file system, then delete it. 
3 - Open your solution in Visual Studio.
 4 - Open any .resx file (i.e.:AppResources.resx
5 - Modify the file by just adding an empty space
after an XML node.
6 - Save your changes.

After that, simply run your solution and it should work s the Resource.Designer.cs should regenerate (to make sure open it and you will see it is not empty).

Could you guys please let me know if any of the above works for you? ...if not please let me know so we can investigate further.  

Regards and thanks,
JP

**Comment by HomeroLara** [comment] 2019-04-08 22:43
Hi @jpbrocca, thanks for your reply.

I was finally able to build and successfully deploy the Android project. After several attempts to build the project, I finally decided to:
- re-install VS for Mac 2019
- re-installed several Android APIs
- re-installed the Android SDK Tools and the Android SDK Build Tools.

After doing the steps listed above, the Android project built and deployed successfully. 

Thanks for your quick response.

**Comment by jpbrocca** [comment] 2019-04-08 22:45
Oh, those are great news @HomeroLara !
Thanks for letting us know.

@rafaelYstoc do you have any update on this?

Best regards and thanks,
JP

**Comment by ismaelf** [comment] 2019-04-10 00:10
I was having the same issues, with Visual Studio on Windows and on Mac. Following the steps on @jpbrocca post, I got it working!

**Comment by MehmetCANKAYA** [comment] 2019-04-10 12:55
I'm giving these erors. What can I do?
Visual studio professional on win 10. 
Grial ui kit v3 pro 
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_StatusBar_EventContent. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Platform_V11_AppCompat. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Dimension.abc_action_bar_progress_bar_size. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Platform_V14_AppCompat. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Platform_V11_AppCompat. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Time_Media. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Title. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Animation.design_fab_out. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Attribute.textColorError. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Color.design_textinput_error_color_dark. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V14_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Boolean.abc_config_closeDialogWhenTouchOutside. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Animation.design_fab_in. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_StatusBar_EventContent_Info. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Platform_V11_AppCompat_Light. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Info. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Animation.tooltip_exit. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Platform_V14_AppCompat_Light. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Color.abc_tint_switch_thumb. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Styleable.DesignTheme_textColorError. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Boolean.abc_config_showMenuShortcutsWhenKeyboardPresent. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Layout.tooltip. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Styleable.DesignTheme_textColorError. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V21_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Platform_V14_AppCompat_Light. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V11_Theme_AppCompat_Dialog. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V12_Widget_AppCompat_EditText. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Info_Media. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Dimension.abc_action_bar_progress_bar_size. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Color.design_textinput_error_color_light. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V12_Widget_AppCompat_EditText. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_StatusBar_EventContent_Time. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Boolean.abc_config_showMenuShortcutsWhenKeyboardPresent. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V11_ThemeOverlay_AppCompat_Dialog. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Widget_Design_CoordinatorLayout. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V11_ThemeOverlay_AppCompat_Dialog. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Platform_V14_AppCompat. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V11_Theme_AppCompat_Dialog. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_StatusBar_EventContent_Title. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Line2_Media. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Title_Media. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Attribute.textColorError. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V26_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Widget_AppCompat_NotificationActionContainer. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_StatusBar_EventContent_Line2. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V12_Widget_AppCompat_AutoCompleteTextView. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.String.abc_action_bar_home_description_format. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V12_Widget_AppCompat_AutoCompleteTextView. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_Widget_Design_AppBarLayout. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V11_Theme_AppCompat_Light_Dialog. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Styleable.MediaRouteButton_buttonTint. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Line2. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Widget_AppCompat_NotificationActionText. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Animation.tooltip_enter. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Widget_Design_CoordinatorLayout. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Color.error_color_material. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Base_V11_Theme_AppCompat_Light_Dialog. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Layout.abc_action_bar_view_list_nav_layout. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Time. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.Platform_V11_AppCompat_Light. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Style.TextAppearance_AppCompat_Notification_Media. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.Boolean.abc_config_closeDialogWhenTouchOutside. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		Skipping k12Mobile.Droid.Resource.String.abc_action_bar_home_subtitle_description_format. Please check that your Nuget Package versions are compatible.	k12Mobile.Droid			
Warning		There is no available connection to the Mac, hence the task Xamarin.MacDev.Tasks.CollectBundleResources will not be executed	k12Mobile.iOS			
Warning		Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.	k12Mobile.iOS			
Warning		There is no available connection to the Mac, hence the task ResolveUniversalTypeIdentifiers will not be executed	k12Mobile.iOS			
Warning		No enough information has been provided to MSBuild in order to establish a connection to a Remote Server. The project 'k12Mobile.iOS' will continue building offline	k12Mobile.iOS			
Warning		Found conflicts between different versions of "System.Net.Http" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	k12Mobile.iOS

**Comment by rafaelYstoc** [comment] 2019-04-10 14:18
I try to update SDK with no success, but doing this solution everything work pretty fine:

1 - Close Visual Studio.
2 - Locate the file Resource.Designer.cs in your file system, then delete it.
3 - Open your solution in Visual Studio.
4 - Open any .resx file (i.e.:AppResources.resx
5 - Modify the file by just adding an empty space
after an XML node.
6 - Save your changes.

My project is the full solution with pro license. 

Thanks guys!

**Comment by MehmetCANKAYA** [comment] 2019-04-10 19:05
> I try to update SDK with no success, but doing this solution everything work pretty fine:
> 
> 1 - Close Visual Studio.
> 2 - Locate the file Resource.Designer.cs in your file system, then delete it.
> 3 - Open your solution in Visual Studio.
> 4 - Open any .resx file (i.e.:AppResources.resx
> 5 - Modify the file by just adding an empty space
> after an XML node.
> 6 - Save your changes.
> 
> My project is the full solution with pro license.
> 
> Thanks guys!

Thank for your solution. But it dosent work for me. All the sdk etc up to date. Why is giving an error??

**Comment by jpbrocca** [comment] 2019-04-10 21:20
Hi @MehmetCANKAYA,

It seems you are getting warnings only...Are you also getting errors that stop you from running the app?

From your log it seems to be an issue with packages version.
- Which is your Android SDK installed version?
- Did you just get those warnings just running your downloaded Grial solution for the first time or did you add additional packages?

Regards and thanks,
JP

**Comment by MehmetCANKAYA** [comment] 2019-04-11 07:05
> Hi @MehmetCANKAYA,
> 
> It seems you are getting warnings only...Are you also getting errors that stop you from running the app?
> 
> From your log it seems to be an issue with packages version.
> 
> * Which is your Android SDK installed version?
> * Did you just get those warnings just running your downloaded Grial solution for the first time or did you add additional packages?
> 
> Regards and thanks,
> JP


Hi jpbrocca,

I'm getting warnings that stop me from running the app. 

I got those warnings  downloaded Grial solution for the first time and the project that has additional packet. Both of them gived warnings and stopped the runnnig.

I will chech SDK installed version and feedback you.

Thank you for your interest. Mehmet. Thank you.

**Comment by HomeroLara** [comment] 2019-04-11 17:57
@MehmetCANKAYA

Have you tried un-installing and re-installing your Android SDK Tools and Android SDK Build Tools?

I think that was the root cause to my issue.

**Comment by MehmetCANKAYA** [comment] 2019-04-11 19:32
https://youtu.be/0qXSRauEJvM

**Comment by MehmetCANKAYA** [comment] 2019-04-11 19:35
> @MehmetCANKAYA
> 
> Have you tried un-installing and re-installing your Android SDK Tools and Android SDK Build Tools?
> 
> I think that was the root cause to my issue.

thank you HomeroLara, for your interst.

I up to date Android SDK but un-isntall. I will try. thanks.

**Comment by jpbrocca** [comment] 2019-04-11 19:38
Hi @MehmetCANKAYA,

Could you show us your Android SDK installed version?
I am suspect your issue could be related to what @HomeroLara mentioned.

I don't understand when you said:

> I up to date Android SDK but un-isntall.

Did you install latest Android SDK and uninstalled it?

**Comment by MehmetCANKAYA** [comment] 2019-04-11 19:46
> Hi @MehmetCANKAYA,
> 
> It seems you are getting warnings only...Are you also getting errors that stop you from running the app?
> 
> From your log it seems to be an issue with packages version.
> 
> * Which is your Android SDK installed version?
> * Did you just get those warnings just running your downloaded Grial solution for the first time or did you add additional packages?
> 
> Regards and thanks,
> JP

https://youtu.be/zxNLkNa5jZg

**Comment by MehmetCANKAYA** [comment] 2019-04-11 20:25
> Hi @MehmetCANKAYA,
> 
> Could you show us your Android SDK installed version?
> I am suspect your issue could be related to what @HomeroLara mentioned.
> 
> I don't understand when you said:
> 
> > I up to date Android SDK but un-isntall.
> 
> Did you install latest Android SDK and uninstalled it?

Hi @jpbrocca
I installed latest Andoid SDK. can we connection via Team view?

**Comment by dirivero** [comment] 2019-04-11 20:54
Hi @MehmetCANKAYA,
Can you try running the attached Xamarin.Forms clean project in your android emulator?
[EmptyApp.zip](https://github.com/UXDivers/Grial-UI-Kit-Support/files/3070551/EmptyApp.zip)

**Comment by MehmetCANKAYA** [comment] 2019-04-11 21:01
> Can you try running the attached Xamarin.Forms clean project in your android emulator?

Hi dirivero.
Okey.

**Comment by MehmetCANKAYA** [comment] 2019-04-11 21:27
> Hi @MehmetCANKAYA,
> Can you try running the attached Xamarin.Forms clean project in your android emulator?
> [EmptyApp.zip](https://github.com/UXDivers/Grial-UI-Kit-Support/files/3070551/EmptyApp.zip)

This project is working. Giving no erors.

**Comment by MehmetCANKAYA** [comment] 2019-04-11 21:34
I tried all the solution method offered me. but still giving an error.
We could'nt solve. Thanks

**Comment by dirivero** [comment] 2019-04-11 21:49
Good. Can you try again? This time the attached project points to Android 9.0 as Grial does.
[EmptyApp2.zip](https://github.com/UXDivers/Grial-UI-Kit-Support/files/3070719/EmptyApp2.zip)

Here there's an explanation on how to install the Android 9 SDK (or check if already installed):
https://devblogs.microsoft.com/xamarin/xamarin-android-9-0-p-preview/

**Comment by MehmetCANKAYA** [comment] 2019-04-12 06:07
> Good. Can you try again? This time the attached project points to Android 9.0 as Grial does.
> [EmptyApp2.zip](https://github.com/UXDivers/Grial-UI-Kit-Support/files/3070719/EmptyApp2.zip)
> 
> Here's an explanation on how to install the Android 9 SDK (or check if already installed):
> https://devblogs.microsoft.com/xamarin/xamarin-android-9-0-p-preview/

Thank you @dirivero.
I will try the project as soon as possible. I'm not on my computer.

Regards and thanks, Mehmet

**Comment by MehmetCANKAYA** [comment] 2019-04-12 21:19
> Good. Can you try again? This time the attached project points to Android 9.0 as Grial does.
> [EmptyApp2.zip](https://github.com/UXDivers/Grial-UI-Kit-Support/files/3070719/EmptyApp2.zip)
> 
> Here's an explanation on how to install the Android 9 SDK (or check if already installed):
> https://devblogs.microsoft.com/xamarin/xamarin-android-9-0-p-preview/

Hi @dirivero. 
I fully installed Android 9 SDK. 
EmptyApp2 project isn't giving an error. But my project that dowloaded from Grial is giving an eror.

Sdk manager  status.
![1](https://user-images.githubusercontent.com/18666921/56066858-cc399180-5d81-11e9-8417-29506343df98.png)
![2](https://user-images.githubusercontent.com/18666921/56066876-d78cbd00-5d81-11e9-9bb4-de0d875f543c.png)

**Comment by MehmetCANKAYA** [comment] 2019-04-12 21:27
EmptyApp2.zip project.
![3](https://user-images.githubusercontent.com/18666921/56067072-803b1c80-5d82-11e9-9ec5-b8d19892a831.png)

My project debug result

![4](https://user-images.githubusercontent.com/18666921/56067176-e7f16780-5d82-11e9-875f-3840cfbdaeb1.png)

**Comment by dirivero** [comment] 2019-04-12 23:19
OK. Now that you have Android 9, can you try this?
 - close visual studio
 - remove the **obj** and **bin** folders from both the .net standard and the android projects
 - open VS and run once again

**Comment by MehmetCANKAYA** [comment] 2019-04-13 00:13
Thanks dirivero. But it is giving same errors.
I removed the obj and bin folders from both the .net standard and the android projects that you say.
Not successful.
What will do that next step?

os: Win 10 enterprise LTSC
Visual Studio professional 2017

**Comment by MehmetCANKAYA** [comment] 2019-04-13 01:18
> OK. Now that you have Android 9, can you try this?
> 
> * close visual studio
> * remove the **obj** and **bin** folders from both the .net standard and the android projects
> * open VS and run once again

thrown  this error below.

![image](https://user-images.githubusercontent.com/18666921/56072769-e9cb2300-5da2-11e9-8f07-bc6a34fa47e1.png)

**Comment by jpbrocca** [comment] 2019-04-13 12:32
Hi,
It seems now you are getting an error on ffimageloading. Most probably you have updated its package and that is why you get this error. Try to downgrade it to the version number you get when you download your Grial solution. 

Let me know how it goes. 

Regards 
JP

**Comment by MehmetCANKAYA** [comment] 2019-04-13 20:58
Hi @jpbrocca 
getting an error like that at this time.  is there a maintenance etc. on server?
![5](https://user-images.githubusercontent.com/18666921/56085184-d1f9aa80-5e47-11e9-87be-e9b275bb9dd9.png)

**Comment by jpbrocca** [comment] 2019-04-13 22:03
Hi @MehmetCANKAYA,
I tried and it seems it is working.

Did you follow the steps on the docs about setting up the nuget server? 
http://docs.grialkit.com/working-locally.html#working-locally-setting-up-uxdivers-nuget-source

You could also try to reach that url from your browser to check if the private nuget server is properly configured in Visual Studio:
http://nuget.uxdivers.com/api/v2/package/uxdivers.grial/3.0.20

To help you troubleshoot any related issue please check the following link:
http://docs.grialkit.com/troubleshooting.html#troubleshooting-uxdivers-nuget-source-issues

Let me know how it goes. 

Best regards 
JP

**Comment by MehmetCANKAYA** [comment] 2019-04-14 18:40
Hi jpbrocca,
I uninstalled v.s 2017 then installed vs 2019 and worked.
Thanks.

**Comment by jpbrocca** [comment] 2019-04-14 20:15
Hi @MehmetCANKAYA,

Great to hear that!
I am closing this issue the, but feel free to reopen as needed. 

Regards 
JP

**Closed by jpbrocca** 2019-04-14 20:15 UTC
