### ISSUE TITLE
Navigation Page barbackgroundcolor is not changing , remains white 

### ISSUE THREAD

**Issue by ShamineDsouza** [UXDivers/Grial-UI-Kit-Support#748] opened 2020-09-14 11:36 UTC
I have full Xamarin Grial version , and the application in android is working fine .
But is not working in IOS Xamarin Navigation Bar. 
Navigation Page bar background color is not changing , remains white.   

IOriginal 
     <Style TargetType="NavigationPage" ApplyToDerivedTypes="true">
              <Setter Property="HasNavigationBar" Value="True" />
                <Setter Property="BarBackgroundColor"
					Value="{ DynamicResource NavigationBarStartBackgroundColor }" />
                <Setter Property="BarTextColor"
					Value="{ DynamicResource NavigationBarTextColor }" />
                <Setter Property="BackgroundColor"
					Value="{ DynamicResource BasePageColor }" />
                <Setter Property="grial:GrialNavigationPage.BarBackground"
					Value="{ DynamicResource NavigationBarGradient }" />
                <Setter Property="grial:GrialNavigationPage.BarBackgroundHeight"
					Value="600" />
            </Style>

-----------------------------------------------------------------------------------------------------------------

  <grial:LinearGradient	x:Key="NavigationBarGradient" Angle="95">
        
        <grial:GradientColor Color="{ StaticResource NavigationBarEndBackgroundColor }"    Opacity="0.9" />
        <grial:GradientColor Color="{ StaticResource NavigationBarStart2BackgroundColor }" Opacity="0.9" />
        <grial:GradientColor Color="{ StaticResource NavigationBarStart1BackgroundColor }"  Opacity="0.9" />
        <grial:GradientColor Color="{ StaticResource NavigationBarStartBackgroundColor }"  Position="0.25" Opacity="0.7"  />

Have tried adding manually as well  for each page.

MainPAge= New NavigationPage(Page1() {
BackGroundColor = Color.Orange
});

PLease need urgent help . My android project is fully ready. And I am very close on deadline.
![IMG_20200914_142734](https://user-images.githubusercontent.com/25946929/93080634-b034d080-f696-11ea-9f1e-f97564987015.jpg)

VS 2019
Xamarin Forms 4.4
Grial 3.0

**Comment by jpbrocca** [comment] 2020-09-14 17:09
Hello @ShamineDsouza,

A couple of questions here:

- Could you update Grial packages to the latest version? We fixed issues in regards iOS Navigation Bar in Grial 3.0.54 and also in Grial 3.0.70.
- Do you get the same result even with a downloaded solution from Grial Web Admin (without making any change)?
- Last question: are you reproducing the issue also in real devices or just in the emulator?

Regards
JP

**Comment by ShamineDsouza** [comment] 2020-09-23 06:01
I  updated to the latest version . Now the issue seems to be resolved for navigation bar.  
I am testing the same on emulator. 
 I did not check with the original solution. 

I have observed another issue  that the text alignment is not proper . I have two languages Arabic and English . in android it aligns them  properly  to right and left accordingly .
However  in IOS  there seems to be a problem, If I set flow direction , even English moves towards the right.

**Comment by jpbrocca** [comment] 2020-09-23 12:02
Hello @ShamineDsouza,

Can you paste the code block where you set FlowDirection?

**Comment by ShamineDsouza** [comment] 2020-09-23 12:37
<Label
				Grid.Row="0"
				Grid.Column="1"
                Grid.ColumnSpan="2"
				Style="{ StaticResource LabelBoldStyle }"
				Text="{ Binding Name }"
                FlowDirection="RightToLeft"
				FontSize="14"
				VerticalOptions="Center" 
                HorizontalTextAlignment="Start"
                HorizontalOptions="FillAndExpand" />

            <Label
				Grid.Row="1"
				VerticalOptions="Center"
                HorizontalOptions="FillAndExpand"
                HorizontalTextAlignment="Start"
                FlowDirection="RightToLeft"
				Grid.Column="1"
                Grid.ColumnSpan="2"
				Text="{ Binding Description }"
				LineBreakMode="WordWrap"
				FontSize="14" />

**Comment by jpbrocca** [comment] 2020-09-28 13:29
Hi @ShamineDsouza,
I am closing this issue now since you opened 752:
https://github.com/UXDivers/Grial-UI-Kit-Support/issues/752

I will continue there.

Regards,
JP

**Closed by jpbrocca** 2020-09-28 13:29 UTC
Labels: in review
